### ISSUE TITLE
Having trouble to add css module loader

### ISSUE THREAD

**Issue by intelcoder** [storybooks/storybook#1072]
I use css module and postcss lib for my project. I tried to config webpack.config.js by using the full control mode. However, it keep throwing error like below.
```
events.js:163
      throw er; // Unhandled 'error' event
      ^
```
My storybook version is like below.
`  "@storybook/react": "^2.21.0"
`

Here is my ./storybook/webpack.config.js. 

```

const  genDefaultConfig = require('@storybook/react/dist/server/config/defaults/webpack.config');


module.exports = function(config, env) {
  let extendedDefaultConfig = genDefaultConfig(config, env);

  // Make whatever fine-grained changes you need
  extendedDefaultConfig.module.rules.push(
    {
      test: /\.css$/,
      use: [
        'css-loader?importLoaders=1&modules&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
      ]
    }
  );
  return extendedDefaultConfig;
};


```

Thanks for taking your time to read this.

**Comment by danielduan** [comment]
You'll have to require `@storybook/react/dist/server/config/webpack.config` since the `config/default/webpack.config` already has a CSS loader defined.

Basically how it works is that you're including all the configs in `config/default/webpack` which also includes all the configs in `config/webpack`. By directly including `config/webpack`, you're going to be missing a few loaders. Look at the file in `/src/server/config`

**Comment by ndelangen** [comment]
This webpack config is for webpack 1, please not pretty soon storybook will move over to webpack 2. And in fact you can try the alpha containing webpack 2 right now.

Webpack 2 configures the loaders / rules a bit differently. Check out this guide right here: https://webpack.js.org/guides/migrating/#components/sidebar/sidebar.jsx

---

I cannot deduce exactly what the problem is you are having, can you post the full stack-trace?

What might be happening is that `@storybook/react/dist/server/config/webpack.config` contains a rule for `css` and now you're appending a second one. I don't think this will work. But I can't say for use because I don't know what webpack loaders exactly do in such a scenario.

I hope this helps you.

**Comment by danielduan** [comment]
Please reopen this issue if there's still a problem.
