### ISSUE TITLE
use proptypes from standalone package

### ISSUE THREAD

**Issue by macrozone** [storybooks/storybook#1540]
storybook-native still uses `import React, { Component, PropTypes } from 'react';`

which does not work anymore in react 16.0.0.beta.x

it should use package prop-types

**Comment by ajwhite** [comment]
Given that we [don't specify a `react` dependency version](https://github.com/storybooks/storybook/blob/ac2c8bdeaafdc5671c5d4b1d2c54e2fe7f348d92/app/react-native/package.json#L78), I'd like to look towards @kentcdodds's solution for this `glamorous`, https://github.com/paypal/glamorous/commit/14970c1bb59d1408d3066d209dafa356b5ce3173.

Essentially - use `prop-types` if they exist and `React` is of a certain version, otherwise use `React.PropTypes`. 

I think the right move is to continue to be flexible with the `React` version since, as a tool, we don't necessarily want to enforce requirements onto the projects using the tool.

**Comment by macrozone** [comment]
@ajwhite that's true, but i want to highlight that the prop-types package work with react 14, 15 and 16: https://www.npmjs.com/package/prop-types

**Comment by Hypnosphi** [comment]
> `React.version.slice(0, 4) === '15.5'`
Looks like this will warn in 15.6 and break in 16

**Comment by shilman** [comment]
@ajwhite why complicate things? Shouldn't we just move to `prop-types` and be done with it?

**Comment by ajwhite** [comment]
>  but i want to highlight that the prop-types package work with react 14, 15 and 16

Given @macrozone's findings -- sounds like we can move over without a problem on the compatibility fronts 👍

**Comment by danielduan** [comment]
https://github.com/storybooks/storybook/pull/1674 we've moved everything over.
