### ISSUE TITLE
Options for hierarchy

### ISSUE THREAD

**Issue by sapkra** [storybooks/storybook#1565]
Options to modify the size and the animation speed of the hierarchy.

**Comment by michaltaberski** [comment]
@sapkra I don't like the slow tree animations neither.

I made a pull request where you can set a flag `sidebarAnimations` to `false` in order to disable the animations. 

https://github.com/storybooks/storybook/pull/1601

@ndelangen could you take a look at https://github.com/storybooks/storybook/pull/1601 and tell me what you think?

**Comment by ndelangen** [comment]
I think that it's merged!

I hope it's ok if I close this issue then.
