### ISSUE TITLE
build-storybook fails with storybook-addon-jsx

### ISSUE THREAD

**Issue by nicolaskruchten** [storybooks/storybook#1774]
When I activate https://github.com/Kilix/storybook-addon-jsx and run `build-storybook` I get the following error:

```
Building storybook ...
Failed to build the storybook
static/preview.1df973a972c249728195.bundle.js from UglifyJs
Invalid assignment [static/preview.1df973a972c249728195.bundle.js:44048,34]
```

It seems like Uglify is failing on some ES6 input, specifically an arrow function (that's what's on line 44048 in that JS file, and it's the first line where an arrow function appears).

To reproduce:

1. clone this: https://github.com/plotly/react-pivottable/tree/jsx-addon-bug
2. `npm install`
3. `npm run build-storybook`

I've filed an issue in the addon repo (https://github.com/Kilix/storybook-addon-jsx/issues/16), but I wonder if this isn't a framework problem...?

**Comment by tmeasday** [comment]
@nicolaskruchten I'd say the problem is this:  https://github.com/algolia/react-element-to-jsx-string/issues/140

**Comment by tmeasday** [comment]
I suspect it will get fixed by https://github.com/storybooks/storybook/pull/1733

**Comment by tmeasday** [comment]
An alternative (workaround) solution is to alter the webpack config to compile just the relevant node modules. This works:

```js
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: /node_modules\/(stringify-object|get-own-enumerable-property-symbols)/,
      },
```

(I know all this because I ran into this bug in a different context just the other day)

**Comment by nicolaskruchten** [comment]
Ah, thanks @tmeasday that's really helpful!

Question: when you say "alter the webpack config" which config do you mean? Do you mean via the "full control" mechanism here https://storybook.js.org/configurations/custom-webpack-config/ ?

**Comment by nicolaskruchten** [comment]
Ah, I see there's a solution with full-control mode here: #1570

**Comment by leetercola** [comment]
I tried the workarounds here and [#1570](https://github.com/storybooks/storybook/issues/1570) but they either break resolution, or loaders. I concur with the other discussion on 1570 why is there an uglify plugin against src and not babel parsed code? Either pull the plugin or pre parse it with babel before the uglify.

**Comment by Hypnosphi** [comment]
@leetercola the thing is that loaders (including `babel-loader`) don't process files from `node_modules` by default

**Comment by tmeasday** [comment]
I don't think you can selectively apply uglify, it will run over the whole webpack-ed bundle, which includes your code, and things from `node_modules`. As @Hypnosphi points out, typically you do not run babel over `node_modules` (because it'd be hella slow and is unnecessary).

Of course it's no longer true that it's unnecessary if people are going around publishing uncompiled ES6 packages that are not targeted at the browser. This is what's happening in this case. So my solution above is to tweak the webpack config to ask it to selectively apply babel inside `node_modules`.

@leetercola are you sure that you implemented what I was talking about above correctly? I have not solved this particular problem for `storybook-build` but I had the exact same problem in my app and the config above solved it.

**Comment by tmeasday** [comment]
Meanwhile I should add this whole situation is messed up and it should not be your responsibility to fix it.

It doesn't look like the original package author is likely to change his stance on pre-compiling his package, so I would say the next best solution in the short term is the author of storybook-addon-jsx (@Kilix) should figure out a way to depend on a pre-compiled version of `react-element-to-jsx-string`. 

Otherwise, this should fix it eventually: https://github.com/storybooks/storybook/pull/1733
