### ISSUE TITLE
Question: Resetting knobs from a decorator

### ISSUE THREAD

**Issue by morgs32** [storybooks/storybook#1842]
Is it possible? I've tried pulling in the channel and emitting `addon:knobs:reset` but nothing works!

**Comment by shilman** [comment]
It should be possible. If it's not working for you, one possibility is that you are emitting the event on the wrong channel. The storybook channel is a singleton, and it's possible for there to be multiple instances of the channel, in which code A is emitting an event on channel 1, and code B is listening for that event on channel 2.

This has happened to me when I was developing my own addon and trying to install it on a local project using `npm link`. Specifically, my app had the following structure under `node_modules`:

```
...
@storybook/addons
...
my-custom-addon/
   ...
   node_modules/@storybook/addons
...
```

If you poke around in your project and find duplication (of addons, or potentially of `@storybook/react` etc.) then funny things like that can happen. Not sure this is your problem, but if it is, try using `file:` dependencies rather than `npm link`.

**Comment by UsulPro** [comment]
@morgs32, In addition to what @shilman pointed out, possible problem could be related to the direction of emitting:

Currently, you can send messages only from preview to manager or from manager to preview. But in this case all event listeners for `addon:knobs:reset` are on preview side (where your stories and decorators are). And I guess you're emitting from preview side as well. So your message isn't handled by them. 'Reset' button works because it emits from manager side of channel.

Actually, #1407 changes this behavior and allows to send messages in both directions. So possible your code will start to work with v3.3-alpha.
