### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by sanphandinh** [storybooks/storybook#1982]
When I run getstorybook command in create-react-app project. It can't work and show message:
"Adding storybook support to your "Create React App" based project(node:9436) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: un
able to verify the first certificate"

**Comment by danielduan** [comment]
can you post the full error log?

It sounds like there might be a certificate issue with npm install. You might be using an internal npm server or perhaps behind a corporate firewall that messes with npm downloads?

**Comment by Zeophlite** [comment]
I have the same issue, and I'm behind a corporate firewall.  `npm install` works correctly (I have used `npm config set proxy` )

```
$ getstorybook

 getstorybook - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
 • Adding storybook support to your "Create React App" based project(node:14192) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: connect ETIMEDOUT 151.101.76.162:80
(node:14192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by alexlurvey** [comment]
I've been trying to work around this. I'm on node v8.6.0. It seems like the problem is when latest-version tries tries to require packages in storybook's generators. I added a catch block to latest-version's index.js file local where storybook was installed globally. 

<npm-global-dir/lib/node_modules/@storybook/cli/node_modules/latest-version/index.js
`module.exports = name => packageJson(name.toLowerCase()).then(data => data.version).catch(e => console.log(e));`

This allowed allowed the getstorybook command to complete and 'yarn run storybook' loads the page. Not sure if anything would be broken since I've never used storybook before.

So a workaround to run the command would be either adding that catch block or running:
`NODE_TLS_REJECT_UNAUTHORIZED=0 node <npm-global-dir>/lib/node_modules/@storybook/cli/bin/generate.js`

Although, using the cafile I use for npm would be ideal.

**Comment by arikaa** [comment]
I added the solution @alexlurvey created and was able to run storybook!
