### ISSUE TITLE
action adding problem?

### ISSUE THREAD

**Issue by gperdomor** [storybooks/storybook#2065]
I have this
```javascript

const fn = () => action('something!');

storiesOf('Demo', module)
  .add('with fn', () => <button onClick={fn}>Hello Button</button>)
  .add('with closure', () => <button onClick={action('clicked')}>Hello Button</button>);
```

The last story works, but the other not!... Why?

**Comment by Hypnosphi** [comment]
`action('something')` returns a function so what you want is this:
```js
const fn = action('something!');
```

**Comment by matart15** [comment]
this line. 
https://github.com/storybooks/storybook/blob/master/addons/actions/src/preview.js#L35

@Hypnosphi 
do you know why it must generate function from string like that. Can't it be done with callback?

**Comment by matart15** [comment]
I wanted to do some other stuff before action. 

So i did it like this.
```
const fn = () => {
          console.log('_____________s ')
          // Did other stuffs
          return action('Action 2 clicked').call()
        },
```

**Comment by Hypnosphi** [comment]
> why it must generate function from string like that
There's a comment about it, basically the reason is that we need to use the string you passed as a function name: https://github.com/storybooks/storybook/blob/master/addons/actions/src/preview.js#L27-L30 

> So i did it like this.
That's fine, but you may also want to use [`decorateAction`](https://github.com/storybooks/storybook/tree/master/addons/actions#action-decorators) helper for stuff like that:

```
import { action, decorateAction } from '@storybook/addon-actions'

import Button from './button';

const loggingAction = decorateAction([
  args => {
    console.log('_____________s ');
    return args;
  }
]);

storiesOf('Button', module)
  .add('default view', () => (
    <Button onClick={ loggingAction('button-click') }>
      Hello World!
    </Button>
  ))
```

The main advantage is that you can reuse that `loggingAction` for different actions in different places

**Comment by matart15** [comment]
> we need to use the string you passed as a function name
Thank you.
