### ISSUE TITLE
undefined is not an object (evaluating 'regeneratorRuntime.mark') in react native on generator functions

### ISSUE THREAD

**Issue by macrozone** [storybooks/storybook#2080]
when exporting a generator function * () {}

e.g.

`export default function() * {}`

(which is common when using redux-saga)

this error is thrown in the app when its started with storybook: `undefined is not an object (evaluating 'regeneratorRuntime.mark')`

looks like this issue: https://github.com/facebook/react-native/issues/14838

but all the solution do not work as every babel plugin is installed and even in newer versions. Any idea whats wrong?

**Comment by AndreiCalazans** [comment]
same here 
<img width="400" alt="screen shot 2017-10-23 at 15 00 13" src="https://user-images.githubusercontent.com/20777666/31902518-eb2db0b4-b803-11e7-8b6b-41f66fd3fc20.png">


the solution for me was to to this 
![screen shot 2017-10-23 at 15 03 24](https://user-images.githubusercontent.com/20777666/31902538-fc31e9fc-b803-11e7-8ac6-d9a914b7195f.png)

instead of this
![screen shot 2017-10-23 at 15 03 14](https://user-images.githubusercontent.com/20777666/31902548-02453844-b804-11e7-9b7f-da93d91c0d33.png)

**Comment by JCMais** [comment]
Probably related to this commit https://github.com/facebook/react-native/commit/3103258ca0fd2fb0fda0da1120d9cdf4baf0ca05

> The Babel plugin is part of `react-native-babel-preset`, so as long as you are using this preset you are safe. If not, you should include the specific transformer into your list of plugins, as `react-native-babel-preset/transforms/transform-regenerator-runtime-insertion.js`.

**Comment by geastwood** [comment]
@macrozone which RN version do you have?

I also run into this problem, the reason is after upgrade to 0.49, RN changed entry point from index.ios.js to index.js, make sure the entry point for storybook is also updated.

**Comment by macrozone** [comment]
@geastwood react native 0.49. Yes the entrypoint for storybook was index.js, otherwise it would not work at all

**Comment by matt-oakes** [comment]
To fix this I needed to create another `.babelrc` in the `/storybook` directory with this content:

```
{
  "presets": [
    "react-native"
  ]
}
```

I had to do this even though I had the same file in the root of the project. It doesn't seem to pick this one up.

This workaround is ok, but if possible I think the packager should be able to pick up the babel config from the root repo to avoid duplication and potential issues when it is changed.
