### ISSUE TITLE
Is it possible to combine Storybook with Expo? 

### ISSUE THREAD

**Issue by andrespch** [storybooks/storybook#2216]
this might be a very naive questions but, is there is way one can publish a Storybook app to Expo? what is exactly what the server does? I was thinking, is there a way to host Storybook say on Heroku, and have the RN app point at it?  

Any information you can give me is highly appreciated.

Thanks

**Comment by danielduan** [comment]
Are you talking about something like this? https://github.com/storybooks/storybook/pull/1639

**Comment by andrespch** [comment]
Thanks for your answer @danielduan, it seems that PR attempts to improve an already existing process, are you familiar with a way to achieve this? I would like to host my UI-library on expo, so anyone can access it with the corresponding URL, and then if they wish they can also connect to a session on the browser to see things like documentation, is this even possible?

**Comment by danielduan** [comment]
Honestly it’s a work in progress and unfinished at this point. I think hosting it on Expo is slightly different than his PR.

If you find something that works, please open a PR to include it in our repo.

**Comment by andrespch** [comment]
Thanks for taking the time to answer @danielduan ,  I was also wondering, have you heard of anybody who has integrated storybooks with ReactRX or React-Native  for Web?

**Comment by andrespch** [comment]
so it turns out it works out of the box, I created an ReactXP app with [Create-xp-app](https://github.com/react-native-training/create-xp-app) and then followed the slow guide on for Storybook, I managed to render a simple RX components as a story on the browser, hopefully it will continue to work as it gets more complex.

**Comment by Gongreg** [comment]
Hey @andrespch, Sorry to be late to party. Take a look: 

https://expo.io/@gongreg/rn-storybook-hosted-client-example

And the server:

https://vast-eyrie-45947.herokuapp.com/ (takes ~30s to load because of heroku, but possible to solve, just don't have enough knowledge about heroku).

I will try to do post about how you can achieve it.

Right now:

Server: https://github.com/wix/wix-react-native-storybook-server (very cluttered but I promise to clean it out and probably move it out to separate package)

Client: https://github.com/Gongreg/RNStorybookClientExample (no readme but things should be clear enough).
