### ISSUE TITLE
[Angular] How to render a component that has <ng-content> in the template

### ISSUE THREAD

**Issue by benbrowning** [storybooks/storybook#2817]
### Issue details

I'm pretty new to Angular so this is probably a noob question. I have a button component that uses the <ng-content> tags to project content passed into it when it is used:

Component template:
```js
<button class="button">
    <img src={{iconSrc}} *ngIf="iconSrc" class="icon" />
    <ng-content></ng-content>
</button>
```
but I can't figure out how to pass some content in via my story book story:

```js
storiesOf('Button', module)
  .add('Simple', () => ({
    component: ButtonComponent,
    props: {},
  }))
```

Are there any docs describing the properties that can be used in the object that you return to describe a component? Have tried 'content', 'text' etc but to no avail.

**Comment by igor-dv** [comment]
Can you please try v3.4.0-alpha.5, it contains a "template" prop that you can use instead of the "component"

if your ButtonComponent selector is named `button-component`:

```js
storiesOf('Button', module)
  .add('Simple', () => ({
    moduleMetadata: {
      declarations: [ButtonComponent],
    },
    template: `<button-component> Put your content here </button-component>`,
  }))
```

**Comment by benbrowning** [comment]
@igor-dv Just the ticket. Thanks!

**Comment by omt66** [comment]
How do you add  v3.4.0-alpha.5 to try it?

**Comment by igor-dv** [comment]
@omt66 , just install all the `@storybook/*` related dependencies with the "3.4.0-alpha.5" version. Am I missing something in your question?

**Comment by omt66** [comment]
@igor-dv  sorry I tried that but I am getting some errors.

**Comment by igor-dv** [comment]
What are the errors ?

**Comment by drewbourne** [comment]
Using the `template` & `moduleMetadata` fields with `3.4.0-alpha.8` is working for me. 

I got some errors because I had a custom `webpack.config.js` (from following the [Storybook Angular guide](https://storybook.js.org/basics/guide-angular/)) which appeared to duplicate the module rules for CSS so that that style-loader/css-loader are run twice and error out attempting to parse `exports = module.exports = ...` as CSS. Fix was to remove the `.storybook/webpack.config.js`.

**Comment by teebszet** [comment]
Is this in the docs?

**Comment by teebszet** [comment]
> Can you please try v3.4.0-alpha.5, it contains a "template" prop that you can use instead of the "component"
> 
> if your ButtonComponent selector is named `button-component`:
> 
> ```js
> storiesOf('Button', module)
>   .add('Simple', () => ({
>     moduleMetadata: {
>       declarations: [ButtonComponent],
>     },
>     template: `<button-component> Put your content here </button-component>`,
>   }))
> ```

Is this (should this be) in the docs?

**Comment by benkeil** [comment]
That couldn't be the solution. Why I should write the HTML manually again? It's always in the component. We need a additional `content` property or something to include it in the component's HTML.

**Comment by neryams** [comment]
This is really cumbersome. Now we have to declare the component three(!) redundant times in a MDX story. Once in the Meta, once in the Props, and once in the moduleMetadata.... And then add the html with the selector too. There has to be a better way...

**Comment by SarcevicAntonio** [comment]
is this the "official way" to put some html inside a component?

because it's not really compatible with args therefore not with your whole controls thing, right?

**Comment by ThibaudAV** [comment]
You can use `componentWrapperDecorator` with component 

see exemples here : https://github.com/storybookjs/storybook/blob/d7f0e0f011cbe7e95f6f6663168dd7296ef1bca4/examples/angular-cli/src/stories/core/decorators/componentWrapperDecorator/decorators.stories.ts#L7


pseudo code for this exemple : 

```ts
export default {
  title: 'Button',
  component: ButtonComponent,
  decorators: [
    componentWrapperDecorator(ButtonComponent, (args) => ({ iconSrc: args.iconSrc })),
  ],
  args: { iconSrc: '/icon.png', buttonValue: 'some value' },
} as Meta;

export const WithTemplate = (args) => ({
  template: `Button text {{ buttonValue }}`,
  props: {
    ...args,
  },
});
```

**Comment by SarcevicAntonio** [comment]
while the approach of @ThibaudAV works it feels like a hack

and there are some issues 
* like _having_ to define a template or else i will get my component nested inside itself (because its a hack)
* or the fact i now can't set args per story but have to set them in the default export
* and it also doesn't seem to play nice with the "show code" feature inside Docs-tab

There needs to be an actual solution, please! I'd love to use all these cool new features like the Docs Tab and Controls Tab but it feels like its usage with Angular was an afterthought.

**Comment by dexster** [comment]
@SarcevicAntonio You can have args per story. Just remove them from the default export and add them to the story

```typescript
export default {
  title: 'Button',
  component: ButtonComponent,
  decorators: [
    componentWrapperDecorator(ButtonComponent)
} as Meta;

export const WithTemplate = (args) => ({
  template: `Button text {{ buttonValue }}`,
  props: {
    ...args
  },
});
WithTemplate.args = {
   buttonValue: 'Click me'
}
```

You can also move the componentWrapperDecorator out the default export to the story as well.
```typescript
WithTemplate.decorators = [
    componentWrapperDecorator(ButtonComponent)
];
```

I am seeing my args in "Show code". Now if I could just see my ng-content there as well then this solution would be great

**Comment by anuj-scanova** [comment]
@dexster The solution is not working for `ng-content` with `select`. My `ButtonComponent` looks like
```
<button class="btn btn-primary">
  <ng-content select="[label]"></ng-content>
</button>
```

Now using your code example (without any modification), it does not render the text
<img width="245" alt="Screen Shot 2022-10-01 at 10 32 21 PM" src="https://user-images.githubusercontent.com/105233146/193420213-2ab96ac7-0cd0-4428-8ad2-10c1820b9673.png">

If I remove the `select="[label]"` from the `ng-content`, it works then, but the `@Input()` properties not working then.

**Comment by BigPackie** [comment]
I am using typescript for stories I and had to adjust @ThibaudAV and @dexster  solution otherwise the component would not reflect the changes to angular component `@Input()`  when changing the arguments in storybook `Control` tab or when setting them in code `args={}`.


```ts
//component file, not full code

@Component({
  selector: 'a[myLink]',
  template: `<ng-content></ng-content>`,
  styleUrls: ['./my-link.component.scss'],
})
export class MyLinkComponent {
  @Input() set myLink(variant: LinkVariant | '') {
    if (variant !== '') {
      this.variant = variant;
    }
  }

  private variant: LinkVariant = 'primary';
  @Input() size: LinkTextSize = '100';
  @Input() bold = false;

  @HostBinding('class')
  private get classes() {
    return [
      `text${this.bold ? '-bold' : ''}${'-' + this.size}`,
      `link-class-${this.variant}`,
    ].join(' ');
  }
}

```

```ts
//story file, not full code

export default {
  title: 'ng-Components/Link',
  component: MyLinkComponent,
  decorators: [
    moduleMetadata({
      imports: [MyLinkModule], //component depends on some other components, so it has it's own module
    }),
    componentWrapperDecorator(MyLinkComponent, ({ args }) => {
      return args;
    }),
  ],
} as Meta;

const Template: Story<MyLinkComponent | { ngContent: unknown }> = (args) => ({
  template: `Hello {{ ngContent }}`,  // whole content of this string with replaced ngContent will be correctly inserted, e.g. 'Hello World!'
  props: {
    ...args,
  },
});
export const Default = Template.bind({});
Default.args = {
  bold: true,
  reefLink: 'secondary',
  ngContent: 'World!',
};

```

Usage example of the component:
```html
<a href="google.com" myLink="secondary" [bold]="true" >  Hello World! </a>
```

This might help to some people, although there is a limitation to this approach - it is **not possible to set  attributes native** to the `<a>`  HTML element,for example `href`, unless it is  exposed and wrapped through component's `@Input()`. 

So for a component that is using an attribute selector you cannot modify its native attribute in stroybook using this approach, for that  you must use template @igor-dv .   

I wonder whether there is a nice solution that supports `<ng-content>` with `@Input()` and also **native element attrbiutes** for stories.   Please anybody, let me know.

**Comment by araymond11** [comment]
@dexster Did you find any solution to make it work with ng-content dans select ? I'm facing the same issue as you.

Thanks !

**Comment by Klapik** [comment]
Any news?

**Comment by PKHDK** [comment]
Oh my.. by using the template solution all the control inputs don't do ANYTHING. At least showing them works as @dexster suggested... but these args/controls are useless since the inline template html code is now the "control" but outsiders that can't programm won't be able to quickly change the input properties for a component... which makes using storybook as a whole completely unnecessary
![grafik](https://github.com/storybookjs/storybook/assets/131486811/d57b82ec-136c-4d64-916c-d38a3c3b802a)

There needs to be a better solution, please! I need to know if there is at least some hope or plans to this problem or if I have to shut down storybook in my company immediately before we waste too much time on it... very sad

**Comment by maximLyakhov** [comment]
Thanks @BigPackie! Your solution is the cleanes out there. Used like this:

```
export default {
  title: 'Button',
  component: ButtonComponent,
  args: {size: 'medium', color: 'default', disabled: false},
  decorators: [componentWrapperDecorator(ButtonComponent, ({args}) => args)],
  render: (args: ButtonComponent) => ({props: args, template: 'ng-content'}),
} as Meta<ButtonComponent>
```
<img width="742" alt="Screenshot 2023-09-05 at 13 48 20" src="https://github.com/storybookjs/storybook/assets/75264285/7d643a38-4101-46b6-bc4a-8a0c2fc10986">

**Comment by ChadiEM** [comment]
For `ng-content`, I used a decorator and it worked perfectly.

**Decorator code**
```
export const withNgContent =
  <TArgs = any>(ngContent: string): DecoratorFunction<AngularRenderer, TArgs> =>
  (storyFn, storyContext) => {
    const story = storyFn();
    const metadata = reflectComponentType(storyContext.component);

    const selector = `</${metadata.selector}>`;
    const templateUpdated = story.template.replace(
      selector,
      `${ngContent}${selector}`
    );

    return {
      ...story,
      template: templateUpdated,
    };
  };
```

**Usage**
```
  decorators: [
    ...
    withNgContent('<p>My content</p>'),
  ],
```

You don't need a render anymore :-)
