### ISSUE TITLE
Angular Knobs: URL knob params reset to default on page load

### ISSUE THREAD

**Issue by cwmrowe** [storybooks/storybook#3042]
### Issue details

When using the knobs addon for Angular. When you change the knob default values, the URL is updated to reflect the changes. However if you reload the page or open the link on another tab, the defaults are restored on the page and in the URL. I would expect that the URL would not change and the knob values from the URL would be reflected in the knobs panel and story. 

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/angular 3.4.0-alpha.8`
- `@storybook/addon-knobs 3.4.0-alpha.8`

### Affected platforms 

- Chrome 63, Windows 10

**Comment by Hypnosphi** [comment]
Possible duplicate of #1690

**Comment by tsuyoshiwada** [comment]
Hi, I am having similar problems as well.

https://github.com/storybooks/storybook/blob/d0d6e4fa8b1747641050c929449974a38d34008b/addons/knobs/src/angular/helpers.js#L106-L110

I think that the cause is that `resetKnobs` is called with the above code.

I expect a good solution :smiley:

**Comment by rndmerle** [comment]
Hi.

I'm trying to load stories with specific knob values loaded from the URL parameters (for screenshoting).

It can't work actually because somehow, upon page loading, `setKnobs` is called for each new knob. I mean, it's called for `[{ knob1: {} }]`, then again with  `[{ knob1: {}, knob2: {} }]` and so on.
But it's intended to be called just *once* with all the knobs, so in Panel.js, when the `loadedFromUrl` flag is still false, the values can be loaded from the URL parameters.

Or am I misunderstanding?
