### ISSUE TITLE
Stories not displaying in the web browser- react-native

### ISSUE THREAD

**Issue by bacancy-swaroopa** [storybooks/storybook#3353]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

I created the stories and when running on browser then when I click on the any story
the stories were not displaying in the right pane of the browser
Actually they should display respective stories.

### Steps to reproduce

I installed the storbook and run `npm run storybook` 

Here is the screen shot:

![screen shot 2018-04-04 at 11 53 52 am](https://user-images.githubusercontent.com/31623477/38291773-e1dd0e08-37fe-11e8-8da9-c5806a42f346.png)

Actually commentView story is selected but there is nothing displaye din the right pane

tis is what I have in package.json file

    "@storybook/addon-storyshots": "^3.2.3",
    "@storybook/react-native": "^3.3.15",
    "@storybook/addon-actions": "^3.3.15",
    "@storybook/addon-links": "^3.3.15",
    "@storybook/addons": "^3.3.15"

In app it is working fine but when coming to browser it is not displaying

**Comment by igor-dv** [comment]
React native stories can't be shown in the browser with an out-of-the-box use case - because they are **react-native**. As you can see in the first `Welcome to storybook` screen or in the [Readme](https://github.com/storybooks/storybook/tree/master/app/react-native), you should perform more steps to see them on the device.

If you do want to see them in the browser, you may set up the [react-native-web](https://github.com/necolas/react-native-web). But you should understand that it won't be real native stories.

P.S. Note for the team: we should probably add some big red explicit description to the welcome screen and to the docs, so people won't get confused.

**Comment by danielduan** [comment]
I personally think the web UI is of little value to most developers. We should just default to device UI only - https://github.com/storybooks/storybook/pull/3278

**Comment by joegoodall1** [comment]
Quick question: 

I've got everything up and running for React Native but was wondering if it was possible to have 2 simulators open at the same time, one with the storybook UI and one with the app being developed UI?

If this isn't possible, does it mean I have to shut down the packager to switch between seeing my app and storybook on the simulator?

**Comment by danielduan** [comment]
@joegoodall1 you'll need to run two different packagers, one with the storybook script and the other with whatever you use to bundle your app

**Comment by joegoodall1** [comment]
Thanks for replying so quickly @danielduan.

Can you give me some pointers on how to implement this? Is there a link to an example that is set up and working?

I did try the link [here](https://github.com/storybooks/storybook/tree/master/app/react-native#using-haul-cli) to use the haul packager but that was unsuccessful in running Storybook and our app at the same time.
