### ISSUE TITLE
addon-knobs: null default prop is false after page reload

### ISSUE THREAD

**Issue by CLL80** [storybooks/storybook#3400]
When setting a boolean default prop value, for example, `const shouldBeNullByDefault = boolean('Should Be Null By Default', null);`, the value is `null` but changes to `false` if page is reloaded.

### Steps to reproduce

Clone repo:
`git@github.com:CLL80/storybook.git`

Checkout branch:
`knob-test`

Run storybook

Go to the `withKnobs` story:
http://localhost:9011/?selectedKind=Addons%7CKnobs.withKnobs&selectedStory=tweaks%20static%20values

You will see a `<h3>` that was added at the top of the story. "Should be &#96;null&#96; by default: null".

Reload the page, and `null` will now be `false`. This is important because when it is `false`, the prop will be passed to the component, but if it was `null`, it would not.

### Please specify which version of Storybook and optionally any affected addons that you're running

`@storybook/react 4.0.0-alpha.2`
`@storybook/addon-knobs 4.0.0-alpha.2`

I first noticed this issue using v3.3.10.

**Comment by mshaaban088** [comment]
Just some insights about this issue, this is happening because:
* First time the value is `null`, and serialized as `'null'` (`String`)
* Second time the value is loaded
  * First from stories (value is still `null`)
   * Second from the query params, which has the `serialized` version of type `String`, and when the `deserialization` happens (`value === 'true'`) it ends having value equals to `false`

See [Serialization/Deserialization](/storybooks/storybook/blob/master/addons/knobs/src/components/types/Boolean.js#L47-L48)

**Comment by mshaaban088** [comment]
I'm going to write a small fix for it

**Comment by Hypnosphi** [comment]
Released as [`3.4.2`](https://github.com/storybooks/storybook/releases/tag/v3.4.2)
