### ISSUE TITLE
addon-notes causes story to not render and shows error instead

### ISSUE THREAD

**Issue by terrencewwong** [storybooks/storybook#3442]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Using `addon-notes` causes story to not render. Instead it renders an error "Expecting a valid React element from the story...Seems like you are not returning a correct React element from the story.
Could you double check that?"

![image](https://user-images.githubusercontent.com/5312329/38924911-79ddc472-42fe-11e8-8f34-b3d5f12f1893.png)

### Steps to reproduce

Steps to reproduce:

Here is a link to a repository where I have recreated the problem: https://github.com/terrencewwong/storybook-addon-notes-example

To summarize, this is what I did:

- install react, react-dom, storybook, and addon-notes
- follow the setup instructions for addon-notes
- write a simple story that uses the notes addon

This is the code for the story that is in the repo I linked:

```js
import React from 'react';
import { storiesOf } from '@storybook/react';

const Component = () => <div>Hello</div>

storiesOf('Component', module)
    .add('default', () => <Component />, { notes: 'A very simple component' });
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react v3.4.2`
- `@storybook/addon-notes v3.4.2`

**Comment by Hypnosphi** [comment]
Notes as object is feature is only in `4.0.0-alpha.3` version.
Here are the docs for the stable version: https://github.com/storybooks/storybook/tree/release/3.4/addons/notes

**Comment by terrencewwong** [comment]
Ah sorry that's correct. Thank you!

**Comment by jneuendorf** [comment]
I got the same error as shown above, but the problem was the [incorrect documentation](https://storybook.js.org/addons/using-addons/).

The docs say

```javascript
storiesOf('Button', module).add('with some emoji', () => (
     withNotes('A very simple component')(() =>
        <Button onClick={action('clicked')}>
            <span role="img" aria-label="so cool">😀 😎 👍 💯</span>
        </Button>
    )); // <= there is a bracket too much, I believe ;)
));
```

But the addon's docs say

```javascript
storiesOf('Component', module).add('with some emoji', withNotes('A very simple component')(() => <Component />))
```

So in storybook's documentation the 2nd argument is incorrectly wrapped in a function, I guess.

**Comment by Hypnosphi** [comment]
Fair point @jneuendorf, would you like to send a PR?

**Comment by jneuendorf** [comment]
@Hypnosphi On my way to the PR I noticed, that the docs have already changed significantly: apparently the addons API has changed and already been applied to the docs (see d1d8138fa7d10cc3defb07cb7d94f04ae03faedd by @tmeasday).

So now the question has become:
Why is this not reflected on https://storybook.js.org/addons/using-addons/ ?

Looking through the [package.json](https://github.com/storybooks/storybook/blob/master/package.json) I assume one of these commands must be run in order to deploy the latest docs:

```
docs:build
docs:deploy:ci
docs:deploy:manual
docs:dev
```

**Comment by tmeasday** [comment]
@jneuendorf - this is because `master` of this repository is for the v4 version of storybook which has not yet been released (so the docs are not in sync with it).

You could submit a fix on the `release-3.4` branch (which controls the currently active docs) if you are feeling keen, or just wait for v4, where as you say the problem will resolve itself!

**Comment by jneuendorf** [comment]
@tmeasday Sorry I didn't think of that. Can you guess how long it'll take until `v4` is released? If it's likely still a while I'm gonna create a PR.

**Comment by tmeasday** [comment]
@jneuendorf I'm not totally sure -- @ndelangen? I would say at least a couple of weeks. Haven't done an rc yet.

**Comment by jneuendorf** [comment]
In this case: PR https://github.com/storybooks/storybook/pull/4131 😉

**Comment by ndelangen** [comment]
I think it's worth fixing the docs, would really appreciate that PR @jneuendorf!

**Comment by jneuendorf** [comment]
#4132 should do ;)
