### ISSUE TITLE
Story Parameters for Official Addons

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#3625]
[Story parameters](https://github.com/storybooks/storybook/issues/993) has been implemented for the notes addon in https://github.com/storybooks/storybook/pull/3373

We should also implement it for other official addons as part of the 4.0 release:
- [x] info https://github.com/storybooks/storybook/pull/3697
- [x] jest: https://github.com/storybooks/storybook/pull/3678
- [x] knobs: https://github.com/storybooks/storybook/pull/3675
- [x] viewport #3610
- [x] backgrounds: https://github.com/storybooks/storybook/pull/3676
- [x] options #3958 #3965

**Comment by mshaaban088** [comment]
`viewport` is implemented in #3610

**Comment by tmeasday** [comment]
Wow, that was fast, thanks @mshaaban088!

**Comment by tmeasday** [comment]
Oh. Heh, I see it was done a few days ago. Still great!

**Comment by tmeasday** [comment]
I'll have a go at the jest addon

**Comment by tmeasday** [comment]
@renaudtertrais I am looking at the jest addon and there doesn't seem like much to change. I wondered though if we could make the DX a bit easier using parameters. My suggestion would be that rather than advising people to make a `withTests.js` file to avoid re-importing the test file, we could instead advise the following:

```js
// In `.storybook/config.js`
import { addDecorator } from '@storybook/react';
import { withTests } from '@storybook/addon-jest';
import results from '../.jest-test-results.json';

addDecorator(withTests({ results }));

// In a story file
storiesOf('MyComponent', module)
  .addParameters({ jest: ['MyComponent', 'MyOtherComponent'] })
  .add('This story shows test results from MyComponent.test.js and MyOtherComponent.test.js', () => (
    <div>Jest results in storybook</div>
  ));
```

That way we solve the problem of not wanting to import `jest-test-results.json` in more than one place without needing to add a new file to the project.

Let me know what you think. I am happy to implement the changes (we'll of course continue to support the previous API).

**Comment by Keraito** [comment]
I can work on `info` if nobody is atm

**Comment by tmeasday** [comment]
Sounds great @Keraito

**Comment by Hypnosphi** [comment]
How about backgrounds?

**Comment by tmeasday** [comment]
Seems reasonable. Any reason you left it off the list @shilman?

**Comment by tmeasday** [comment]
How's `info` going @Keraito?

**Comment by Keraito** [comment]
Sorry @tmeasday, thought I had a little bit more time on my hands. I will try to get a PR rolling by the end of this week at latest.

**Comment by tmeasday** [comment]
No worries @Keraito. Just ping me if you do start it, otherwise I might do it soon to wrap this issue up.

**Comment by Keraito** [comment]
Aight, will do!

**Comment by Keraito** [comment]
@tmeasday so I started working on this, implemented the new parameter based pattern with the decorator, and am now writing some additional examples in the `examples/official-storybook`. 

Currently, I have something like this (basically copied the first 2 stories that were already there):
```
storiesOf('Addons|Info.Options.parameters', module)
  .addDecorator(withInfo)
  .addParameters({
    info: {
      text: 'Component should be inlined between description and PropType table',
      inline: true, // Displays info inline vs click button to view
    }
  })
  .add(
    'Inlines component inside story', () => <BaseButton label="Button" />
  )
  .add(
    'Excludes propTypes that are in the excludedPropTypes array', 
    () => <BaseButton label="Button" />, 
    { 
      info: {
        text: 'Label propType should be excluded',
        excludedPropTypes: ['label'],
      }
    }
  );
```

Everything works fine, and the first story is inlined with the corresponding text. The second story however, throws away all the parameters I set in the `addParameters` and overrides it with the only 
` { text: 'Label propType should be excluded', excludedPropTypes: ['label'] }`. So imo it would be better if it would be merged together, particularly that the parameter per story would override any existing values set in the `addParameters`, and adding any non-existing entries. 
The same question also holds between `options` and `parameters`.

**Comment by Hypnosphi** [comment]
Per key sounds enough

**Comment by Keraito** [comment]
@tmeasday so should I do this only for the `info` addon, or for all addons/keys in the 3 param objects?

**Comment by tmeasday** [comment]
@Keraito -- all keys, sorry if that was confusing ;)

**Comment by webholics** [comment]
I would like to hide the addon panel of certain pages (pages which basically just render some Markdown documentation). The way how the options plugin currently works makes this quite difficult to implement because you not only have to set `showAddonPanel` to false on those pages but you also have to set it back to true on all the other stories.

It would be really nice to support the options here to like:
`.addParameters({ options: { showAddonPanel: false }})`

**Comment by Hypnosphi** [comment]
Yeah, `addon-options` is an obvious missing candidate here

**Comment by tmeasday** [comment]
Yes! Let's deprecate the `setOptions(options)` API and do `addDecorator(withOptions(options))` instead!

**Comment by webholics** [comment]
@tmeasday what is important though is that if you do not add the `withOptions` decorator that some previously defined default options are picked up. Otherwise you would be forced to use the decorator in all stories. So we definitely still need the `setOptions`, but maybe more for setting those defaults.

**Comment by tmeasday** [comment]
> Otherwise you would be forced to use the decorator in all stories.

Is this a problem? Can we not just make `addDecorator(withOptions(...))` essentially identical to `setOptions(...)`?

You need the decorator on all stories otherwise the `options` story param will be ignored. Unless you have to add the decorator wherever you add the param, which would be counterproductive IMO.

At first it seems weird that a story decorator could not change the story but simply affect the UI of the manager, but if you think about it, this is what quite a few decorators do in fact (e.g. jest, notes). Perhaps its confusing, but I think a user probably isn't really thinking to hard that its not a decorator but instead something else triggered by the story.

If I was designing it from scratch I might do it a different way, but 🤷‍♂️

**Comment by tmeasday** [comment]
There is an advantage in parameter cascading (story parameters overriding whole-storybook or chapter parameters) -- see this comment: https://github.com/storybooks/storybook/issues/3625#issuecomment-395697496

But yeah, mostly just to be consistent.

**Comment by sapkra** [comment]
Is there any progress for the option plugin? Because this issue is the last open issue in the Storybook 4.0.0 Milestone.

**Comment by tmeasday** [comment]
I was going to look at it in the next day or two. If you are interested it could be a good contribution to make to the project?

**Comment by sapkra** [comment]
Yeah right but I have to say sorry.  I definitely have not the time to contribute to this project right know.
Maybe in some month I will find some time to contribute.

**Comment by tmeasday** [comment]
No problem!

**Comment by igor-dv** [comment]
Let's remove storyshots from the list. It's a new functionality for it, and shouldn't block us.

**Comment by tmeasday** [comment]
Yay! This is now done! Great team effort everyone!

When I next have some free cycles I am going to look at #4010 but I agree its not a blocker for 4.0
