### ISSUE TITLE
Proposal: React Native repository and web interface splitting

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#3710]
### Summary

@Gongreg and I discussed briefly about the developer experience for React Native at React Europe. Most of our concern is around the amount of effort it takes on our end to make changes to the React Native Storybook. The tooling in our monorepo and dependencies on the web Storybook make React Native updates and changes hard to test and time consuming to commit.

#### Remove web interface
As developers of components inside React Native Storybook, the web interface doesn't provide much value aside from selecting the story. We can remedy this by building a better UI for selecting stories inside the Native Storybook. The only addon which works with React Native that relies on the web interface is the `addon-knobs`. I'm not sure how many people currently use this combination, but the user experience is quite awkward and convoluted. We could rebuild an addons panel in React Native if we want to replicate the previous functionality. Also, removing web from native reduces testing complexity for both maintainers on web and native.

1. Remove dependency on `@storybook/react`
2. Fix reloading so that story selection persist on refresh
3. Increase size of story menu so more text fits
4. Add ability to search through stories
5. Add hierarchy to stories
6. Rebuild addon panels in React Native (optional, tbd)

##### Separate out of monorepo
As maintainers of React Native Storybook, there are too many time consuming barriers to making changes to React Native. React Native build and test frameworks are entirely different and it is inefficient to ask web maintainers to install and test React Native dependencies and vice versa. Because the metro bundler doesn't work well with symlinks, we install dependencies via tarballs which need to be completely rebuilt in order to see changes reflected in development environments. This takes anywhere from 1-5 mins and can cost simple changes hours of time. The React Native versioning is technically all breaking changes and isn't reflected in the Storybook React Native semvar versions either.

0. Move React Native code to a separate repo outside of our monorepo
1. Separate versioning from other packages to fully comply with semvar
2. Add detox and snapshot tests for React Native examples
3. Remove tarball building from monorepo and testing CLI
4. Fix CI environments for these changes

CC: @shilman @ndelangen

**Comment by tmeasday** [comment]
This seems reasonable to me. A couple of questions:

1. What packages from the monorepo would you still depend on? `@storybook/core`? Or not even that? Does it make sense to have a common package for the story definition / developer API side?

2. What is the future of an all web interface for RN? Is that something that interests you? Using react-native-web or the new react-native-dom?

**Comment by Gongreg** [comment]
Hey.

I do not agree about removing the web interface.
First the storybook server is used to connect your ide to storybook (webstorm, vs code). Also some people when developing prefer to not have any additional info next to the story they are working. (displaying addons, tree and other things clutter the storybook view in the app). Also if you use some kind of additional documentation it is a lot easier to see it through the web.

What I suggest is to have ability to easily opt out of the web interface. Make onDeviceUI main way to work with RN storybook. To make RN Storybook work we don't need to start storybook server, we don't need to have separate entry point. It already works now, but we need proper documentation about it and update getStorybook templates.

Making addons work shouldn't be too difficult, we already have working knobs: https://github.com/Gongreg/react-native-addon-knobs .
Currently you just render this addon and it works, but we have to think about having common interface for addons in RN Storybook.

About moving RN Storybook out of monorepo, @shilman said he will talk about what tools we could try out to make working with storybook easier. One reason I do like having RN storybook inside monorepo is that more people see it and there is bigger chance that somebody will care about it and do PR's, than having it laying separately. OR we would have to create a completely separate project, where we would have to place both RN storybook and addons that work with it.
Either way I feel like you (main contributors) should have more opinions about moving it out/keeping it here, since I feel really neutral about it.

**Comment by danielduan** [comment]
@tmeasday: 
1. We wouldn't need to depend on core if we remove the web interface. story definition, perhaps.
2. I don't foresee any future with us using react-native compat libraries for the web. Those libraries often aren't 100% feature complete and doesn't replace development within a simulator. They're great for reusing components that have been built for react-native in the web. But as entire development environments, I don't imagine `react-native-web` would replicate all the native <-> react native bridging that's needed for multitouch gestures, native file access, etc. in an efficient manner. Our react-native storybook also supports rendering native components without much modification as well. 

There's probably a good middle ground for the web interface that we can reach here. My opinion is that developers like the web interface only because our react-native interface is terrible for navigating between stories. Please correct me if this is not a correct assumption.

We can probably default to onDeviceUI for future projects. It eases the confusion as to why the web interface has a blank screen.

If we do keep the web interface, it's probably best to keep it inside the monorepo for testing purposes.

Here's my take on the cause of the difficult build and test steps in react-native:
1. the linking between web and react-native is painful. a new tarball needs to be generated in order to be tested with react-native. this makes running an end to end test for react native painful and flakey.
2. testing requires a whole different set of libraries, installing and running them take a significant amount of time (expo or xcode simulator).

If we can somehow fix both of these issues while keeping it inside the monorepo, then most of our development flow issues would be solved.

**Comment by tmeasday** [comment]
> But as entire development environments, I don't imagine react-native-web would replicate ...

@danielduan I guess I didn't mean that `react-native-web` or `react-native-dom` would ever *replace* an on device/simulator experience, my question was more along the lines of "as an active user of storybook RN, how useful would an all-web RN storybook be as a *complement* to the native mode?".

What I am thinking about here is as a documentation tool moreso than a development tool. This is a direction I have been thinking quite a bit about of late (that Storybook should be better as a documentation tool).

> the linking between web and react-native is painful

I wonder about this, simply because the issue isn't necessarily web related, and more is a problem with running an example RN app against a npm module you are actively developing. If that problem can be solved *outside* of the monorepo, then, in theory at least, it should be solvable *inside* the monorepo?

> testing requires a whole different set of libraries, installing and running them take a significant amount of time

This is true, and this is why RN often doesn't get tested, which is frustrating in a few ways. Bringing RN out of the repo will of course mean developers on the monorepo won't *ever* test RN (maybe this is not a problem if RN has no shared dependencies though?). However it's pretty clear that with that arrangement SB/RN is more or less a separate project and unless we try hard it will diverge a fair bit, which will make documentation etc a lot harder.

IMO there is a big benefit in maintaining a similar as possible API, both for users and addon developers, and as much as possible a similar UI. That way if someone writes material about SB (say something like [this](https://learnstorybook.com) ;) ), RN users can analogise easily about how to apply the same techniques. If the projects diverge, this will increasingly not be the case.

**Comment by chawax** [comment]
I agree with @Gongreg about not removing the web interface. At least you should be able to enable it or not. You talked about Knobs addon, but there's also the `actions` addon that needs the web interface for example. Moreover selecting the story is a pain when you use long names.

**Comment by shilman** [comment]
After discussing with @danielduan the other day, I think it makes sense to:
1. Create a standalone RN repo & copy the code
2. Continue publishing from the monorepo until we've evaluated the new repo
3. Preserve the websocket connection which enables the web UI and also @orta 's VS code addon, etc., but possibly split out the web UI aspect of the RN codebase (that could be a config option for `@storybook/react` to publish events to a websocket, or its own package?)
4. Optimize the build and test process in the `storybook-react-native` repo
5. Evaluate where things have landed and whether we can easily backport those refactors/optimizations to the monorepo

**Comment by danielduan** [comment]
> how useful would an all-web RN storybook be as a complement to the native mode
I would see how this would work and be helpful but there's some pretty big caveats that we would have to communicate to the users - the biggest one being that components rendered in the web may not appear or function the same as components rendered in Native. Some of the components in our RN library will definitely not render because they are native iOS or Android components.

I completely agree with the documentation tool part but I wonder if there's a way to somehow integrate or link to an Expo environment instead.

>  developers on the monorepo won't ever test RN (maybe this is not a problem if RN has no shared dependencies
Right. It doesn't make much sense to split the repos if RN is still dependent on the web. The whole concept of monorepo is to put dependencies in the same repo and develop them together.
