### ISSUE TITLE
Proposal: Image snapshots with webdriverio for cross-browser visual regression testing

### ISSUE THREAD

**Issue by alexparish** [storybooks/storybook#3734]
Image snapshots in Storyshots is a fantastic addition and I'd like to start by thanking the contributors for adding this important tool.

In the past I've found that having cross-browser visual regression tests is crucial because, as great as Puppeteer is, it's always the troublesome older browsers such as IE11 that experience regressions. Additionally, most of the engineers I know carry out their development in Chrome so would already spot any regressions that would be caught by Puppeteer while other browsers get forgotten.

This is why I am proposing adding support for webdriverio to image snapshots.

It should be possible to replace references to Puppeteer in [test-body-image-snapshot.js](https://github.com/storybooks/storybook/blob/master/addons/storyshots/src/test-body-image-snapshot.js) with an interface that implements both Puppeteer and webdriverio. There will be some interesting challenges, such as comparing image snapshots for multiple browsers during a test run, but they shouldn't be insurmountable.

**Comment by danielduan** [comment]
I think it's a great idea to screenshot across browsers. There's been discussions around splitting the `storyshot` addon into separate addons - snapshots, screenshots, etc.

If you're interested in helping, feel free to join our slack channel and discuss.

**Comment by igor-dv** [comment]
@alexparish, your arguments sound reasonable, though I can't really advocate about having one or another 3rd party library support, since always will be people that will argue against =) I can just suggest adding both =) So you are welcome to contribute. 

I've separated image snapshots out of the core storyshots api to the `addon-storyshots-puppeteer` package, You can add another one called `addon-storyshots-webdriverio`. It will be a cool addition to this addon.

**Comment by okmttdhr** [comment]
This might help anyone who wants WebdriverIO addon;
https://github.com/andrcuns/addon-storyshots-wdio
