### ISSUE TITLE
addon-info markdown linebreaks not working properly

### ISSUE THREAD

**Issue by JuhQ** [storybooks/storybook#3759]
Line breaks are not working properly with `addon-info` plugin.

When I add multiple lines between text it only add one new line, when it should add more.

pls fix

**Comment by Keraito** [comment]
Hey @JuhQ could you provide us some more information:
- What versions of Storybook are you using?
- A more elaborate example.
- Which part of the info addon are u referring to, markdown or plain text?
- "multiple lines" -> do you mean linebreaks?

**Comment by jonmilner** [comment]
I'm seeing the same issue. Likely due to lines of text rendering as `<div>` rather than `<p>`.

![screen shot 2018-07-11 at 12 54 48 pm](https://user-images.githubusercontent.com/937847/42587741-a6345c46-8509-11e8-9635-7420bcd84967.png)

The problem can be reproduced in the Storybook 4.0 React Official example - https://storybooks-official.netlify.com/?selectedKind=Addons%7CInfo.Markdown&selectedStory=Displays%20Markdown%20in%20description&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

![screen shot 2018-07-11 at 12 51 05 pm](https://user-images.githubusercontent.com/937847/42587565-21b74924-8509-11e8-9595-6b120191df47.png)

**Comment by joshsylvester** [comment]
Seeing the same thing. I'd love to see an this fixed, as this quickly discourages using markdown `withInfo()`

**Comment by remanation** [comment]
If I look at the [code](https://github.com/storybooks/storybook/blob/fa401ece570be10c3025c44750c5eaa8cee9e495/addons/info/src/components/markdown/text.js#L14) it states the following:

> P is oftentimes used as a parent element of `<a>` and `<pre>` elements, which is why `<div>` is used as the outputted element when parsing marksy content rather than `<p>`.

In my opinion it does not make much sense to not render `p` tags.

I see it was changes in this [commit](https://github.com/storybooks/storybook/commit/fa401ece570be10c3025c44750c5eaa8cee9e495#diff-3b399dee6faeb00d28e20107339e26b3).

Could the change be reverted?

As a temp solution I override the rendering of p tags in my storybook config:

```
import infoAddon, { setDefaults } from '@storybook/addon-info';

setDefaults({
  components: {
    p({ children }) {
      return <p>{children}</p>;
    },
  },
});
```

**Comment by jonmilner** [comment]
@Keraito is more info still needed?
