### ISSUE TITLE
Import withInfo in ReactNative gives Bundler error

### ISSUE THREAD

**Issue by cmejet** [storybooks/storybook#3841]
Basic import of withInfo Add On in ReactNative gives error `Module './lib/nestedObjectAssign.js' was required dynamically. This is not supported by Metro bundler`

Happens just by adding `import { withInfo } from '@storybook/addon-info'
import Button from './Button'` couldn't get past this to even add a story using the add on.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react-native 3.4.8
- @storybook/addon-info 3.4.8

**Comment by isacjunior** [comment]
Same problem here.
```
"@storybook/addon-actions": "^3.4.8",
"@storybook/addon-info": "^4.0.0-alpha.14",
"@storybook/addon-links": "^3.4.8",
"@storybook/addons": "^3.4.8",
"@storybook/react-native": "^3.4.8",```

**Comment by paulmichalak** [comment]
Is it possible to get some information about why it isn't supported? I don't see this documented anywhere...

**Comment by Gongreg** [comment]
Sure.

Addon support is documented here: https://github.com/storybooks/storybook/blob/master/ADDONS_SUPPORT.md

Regarding why it is not supported is that info addon a strange addon since it doesn't work inside addon area. It works by rendering info in preview area. React Native doesn't use preview area at all.

There are alternatives to get withInfo functionality for RN:

* notes addon: https://github.com/storybooks/storybook/tree/master/addons/notes (I am not sure why it says it is not supported, it should be).

* jsx addon:
https://github.com/storybooks/addon-jsx

* docgen addon: 
https://www.npmjs.com/package/storybook-addon-docgen

You will also need to update your babelrc to support docgen addon.

I know it is not the same, but currently it is the only way to achieve it.

**Comment by naytun** [comment]
Thanks for detailed response. I like this one informative `https://github.com/storybooks/storybook/blob/master/ADDONS_SUPPORT.md`

**Comment by AnaisGalisson-Mylo** [comment]
Hello guys I don't know if it can helps someone but I made a component to get some doc ( not pretty though)

It gives :
- A component overview
- Some documentation about props (name, type) and you can manually add a description and if the props is required or not)
- Source code of the component and it copy the code to your clipboard when you clic on it.

It's just a component not a library, feel free to edit it.

I tested it with expo but it should also work with pure react native

[](https://github.com/RobinLebhar/with-info-doc-expo-storybook)
