### ISSUE TITLE
SplitChunksPlugin breaks Storybook v4 alpha

### ISSUE THREAD

**Issue by pelotom** [storybooks/storybook#3865]
Attempting to use [WebPack 4's `SplitChunksPlugin`](https://webpack.js.org/plugins/split-chunks-plugin/) breaks the Storybook v4 alpha.

### Steps to reproduce

Make a custom `webpack.config.js` with

```ts
module.exports = (baseConfig, configType, defaultConfig) => ({
  ...defaultConfig,
  optimization: {
    splitChunks: {
      // doesn't seem to make a difference which options are used...
      chunks: 'all',
      name: 'vendors',
    },
  },
});
```

The storybook doesn't render at all, it's just a blank screen. No errors on the console.

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/addon-actions@4.0.0-alpha.13`
- `@storybook/addon-links@4.0.0-alpha.13`
- `@storybook/addon-options@4.0.0-alpha.13`
- `@storybook/addons@4.0.0-alpha.13`
- `@storybook/react@4.0.0-alpha.13`

**Comment by haakenlid** [comment]
I've run into this issue as well when using my existing webpack config with storybook. The fix is simply to omit `splitChunks`. 

```
# .storybook/webpack.config.js
const config = require('../webpack.config.js')
delete config.optimization.splitChunks
module.exports = config
```

This fix is not very obvious, though. Storybook just serves a blank page, and it seems that react never mounts. There are no errors in the console or from wepback, so it's hard to understand exactly what is wrong. 

Could storybook override `optimize.splitChunks` like it does with the webpack config `entry` and `output`? 

Or at least emit a warning in the log, so that it's possible to understand what goes wrong.

**Comment by pelotom** [comment]
> I've run into this issue as well when using my existing webpack config with storybook. The fix is simply to omit `splitChunks`.

Yeah. I would call that a workaround, not a fix.

**Comment by haakenlid** [comment]
> Yeah. I would call that a workaround, not a fix.
I agree.

**Comment by ndelangen** [comment]
I have recently began work on separating the manager's build process from the preview's.

This fixes a ton of issues, including this one.

**Comment by pelotom** [comment]
Looks like this is fixed in storybook v5.
