### ISSUE TITLE
getstorybook: Unexpected token import

### ISSUE THREAD

**Issue by q-jason** [storybooks/storybook#4002]
Sorry, my English is not very good
I'm using storybook

![123123](https://user-images.githubusercontent.com/28495915/43987330-a9f2a1de-9d51-11e8-9347-7c3e9dea3cde.png)
![ver](https://user-images.githubusercontent.com/28495915/43987333-addcc694-9d51-11e8-8642-45c17bccdc8a.png)

Is there any solution？
I looked at other problems and couldn't find a solution

**Comment by noscripter** [comment]
ping @arunoda @Hypnosphi @ndelangen @mnmtanish @shilman , since node.js does not support es modules by default by now, it is not recommended to use `import` directly in your modules, yet the published latest tag was set to be `3.4.11` which uses `import` directly.

So, my suggestion is, either:

-   transpile the code to normal commonjs codes

or:

-  set the latest tag to versions not using `import`, such as `v4.0.0-alpha.22`

@q-jason you can simply use `npm i -g @stroybook/cli@alpha` instead to get it started.

**Comment by noscripter** [comment]
ref https://github.com/storybooks/storybook/issues/3035

**Comment by Hypnosphi** [comment]
> it is not recommended to use import directly in your modules

We use babel-register

**Comment by Hypnosphi** [comment]
@q-jason which version of @storybook/cli is it?
