### ISSUE TITLE
Storybook keyboard shortcuts overlap in IE/Edge and Firefox

### ISSUE THREAD

**Issue by MaDDmin** [storybooks/storybook#403]
That particular combination is taken on Firefox and opens a new private tab instead of toggling the Searchbox as it was meant to.

Here is the relation of Firefox shortcuts in which can be found that particular one: https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly?redirectlocale=en-US&redirectslug=Keyboard+shortcuts#w_windows-tabs

Control + Shift + P = private window
Control + Shift + L = new tab address bar

**Comment by ndelangen** [comment]
So what should the new shortcut be?

**Comment by danielduan** [comment]
Same problem in IE #1691

**Comment by Hypnosphi** [comment]
And Edge as well

**Comment by Hypnosphi** [comment]
As soon as we rename "left panel" to "stories panel" we can introduce `Ctrl + Shift + S` while keeping to support `Ctrl + Shift + L` for backward compatibility. For showing search panel, it seems quite natural to use `Ctrl + Shift + F`.

**Comment by Hypnosphi** [comment]
Oh, `Ctrl + Shift + F` is reserved for fullscreen already.

**Comment by Hypnosphi** [comment]
Here's a table with all the used `Cmd/Ctrl + Shift + ` shortcut keys in major brawsers (sorted by usage data from [caniuse](//caniuse.com)), excluding text field shortcuts, and some highly contextual shortcuts:

|⌘/Ctrl+Shift+|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|[Chrome](https://support.google.com/chrome/answer/157179?hl=en)||+||+||||+|+|+|||+|+||||+||+|||+||||
|[Firefox](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly)|+|+||+||||+||+||||+||+||+||+||+|+|||+|
|[IE 11](https://support.microsoft.com/en-us/help/15357/windows-internet-explorer-11-keyboard-shortcuts)||||||||||||+||||+|||||||||||
|[Safari](https://support.apple.com/kb/PH21483?locale=en_US)||||+||||||||||||||||+|||||||
|[Edge](https://support.microsoft.com/en-us/help/13805/windows-keyboard-shortcuts-in-apps)||||||||||||+|+|||+||+||+|||||||
|[Opera](http://help.opera.com/Linux/9.50/en/keyboard.html)||+||+||||+|+|||+||||+|||+|+|+|+|||||

Those keys are therefore safe for now: `C E F G K O Q X Y`. `U` is also quite safe, it's used only in Opera ("View source of active frame")
We're using `F` for fullscreen, and need to pick four of the remaining ones for other shortcuts instead of `D L P J`.

For search, we could use `Q` (stands for "query") As for panels, I can suggest using the key positions relative to `F`. Here's how available keys are laid out on standard keyboard:

|Q||E|||Y|U||O||
|---|---|---|---|---|---|---|---|---|---|
||||(F)|G|||K||
|||X|C|||||

So here's my suggestion:
* `Q` for search box
* `E` for stories panel
* `C` for addons panel
* `G` for addons panel in right

@ndelangen what do you think?

**Comment by ndelangen** [comment]
I like it @Hypnosphi ❤️
