### ISSUE TITLE
Question about usage with main app

### ISSUE THREAD

**Issue by teekirol** [storybooks/storybook#4130]
In the documentation, it says "Storybook runs outside of your app". 

I'm wondering how people keep the components in their stories in sync with the components in their main app. Do you have to continually make updates in both places?

I tried researching whether it's possible to declare your instance of Storybook as a dependency of your main app, but haven't found anything. Is this recommended?

**Comment by kroeder** [comment]
If you meant that your app and storybook are in the same project then it's just in sync because you develop your components in storybook and just use them in your real app. In my opinion, one of the best parts of storybook is that you don't want to develop your components in your app but just in storybook and use them in your app because storybook is more or less free of side-effects.

If you meant that you have a library with storybook and a seperat app then I'd suggest you develop your components in storybook/your library as well. If you are done you publish it to e.g. npm or a private package manager and install it in your app.

I'm not sure what you mean by "keep the components and their stories in sync"

I hope I did not misunderstood you?

**Comment by ndelangen** [comment]
@teekirol The components never run out of sync, because instead of showing code demoes or examples of code, we write stories, which USE the code / components.

Of course props can change in the component and then not be changed in the stories, or stories could be broken or missing.

But this is exactly the same as unit tests. They provide a validation on your code, your code/components are run.

In unit tests the output is a checklist of (hopefully) green checkmarks.
In Storybook the output is a styleguide & inspectable debuggable environment.

I hope this answers your question!
