### ISSUE TITLE
Alpha Version Static Export Build Script Does Not Respect Env Vars

### ISSUE THREAD

**Issue by jhoffmcd** [storybooks/storybook#4171]
### Bug or support request summary

**What did you expect to happen?**

Running `build-storybook` would respect environment variables such as `NODE_ENV` and `STORYBOOK_*`

**What happened instead?**

Running `build-storybook` seems to not respect environment variables such as `NODE_ENV` and `STORYBOOK_*`

**NOTE**: `start-storybook` does behave as expected.

### Steps to reproduce

Here is a repo where you can test this using the provide configs and NPM scripts:
https://github.com/jhoffmcd/storybook-test-build-script

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.21

### Affected platforms 

Developer tooling?

**Comment by pksunkara** [comment]
Possibly because of [this](https://github.com/sebastian-software/universal-dotenv/commit/e5a2a2b656718d01d9952124b0cbe1f9c9d13166) change in universal-dotenv. But this issue should also include of allowing `REACT_APP_*` and other framework specific environment variables. The way to do it is to use `.env` files which is currently not working. There is a little bit of discussion regarding this [here](https://github.com/storybooks/storybook/pull/3744#issuecomment-419230154)

**Comment by kylemh** [comment]
Is there a good reason why environment variables are being hijacked? `.env` certainly doesn't cover all use cases - especially considering Storybook within CI processes. I think this is a huge limitation that needs to be addressed.

**Comment by kylemh** [comment]
Currently, we're unable to inline environment variables into a command, nor are we able to use `.env` with Storybook. I personally feel like it should be a blocker FWIW. It wouldn't let itself to a great release when nobody is able to define Jest env, Node env, etc.

**Comment by ndelangen** [comment]
Might this be just that our 2 webpack configs dev||prod have gotten a bit out of sync regarding the dotEnvPlugin or something?

**Comment by pksunkara** [comment]
No, the architecture of dotEnvPlugin is wrong IMHO
