### ISSUE TITLE
Issue with Storybook on fresh CRA project

### ISSUE THREAD

**Issue by Keraito** [storybooks/storybook#4211]
Installed Storybook on a fresh CRA project. It compiled and ran perfectly fine, but there seem to be some things missing (font + no borders). Console logs no errors.

![image](https://user-images.githubusercontent.com/5955441/45895369-519f2980-bdd1-11e8-9bd2-bac0f2f38a41.png)

# Versions
- create-react-app -V: 1.5.2
- storybook-cli: current master branch / 4.0.0-alpha.22

**Comment by binomialstew** [comment]
I'm also seeing the same thing on an established project after I updated from `@storybook@4.0.0-alpha.18` to `alpha.20`, but strangely only when installing with `yarn`. When I use `npm install`, storybook fonts load properly.

**Comment by binomialstew** [comment]
I found this to be because `@emotion/provider` has a peerDependency of `@emotion/core`. Yarn installs 0.13.1 in a node_modules that is a child of `@emotion/provider`. Which behaves differently than the one installed in the root node_modules by npm, which is `@emotion/core@0.13.0`. I've added 0.13.0 to my package resolutions for now.

**Comment by igor-dv** [comment]
Checked it with the latest alpha (23) - doesn't happen anymore. 
Please reopen if I am wrong.
