### ISSUE TITLE
Contribution guide for knobs

### ISSUE THREAD

**Issue by ca057** [storybooks/storybook#4216]
Hey!

First of all - thanks for an amazing tool!

I found an issue in the knobs I would like to fix, as I'm affected myself. Apparently, I've problems getting a setup where I can work on a knob and test my changes in one of the examples.

My idea is to use the kitchen sink example to run the actual storybook to test my changes while developing on the knobs.

I've never worked with a monorepo so far, so maybe I'm missing some knowledge here. How can I use the local version of the knobs inside the examples? Is there an elegant way to do it? Can someone point me to the right path? I would be happy if someone could help me out! I'm also happy to improve the contribution guide to help other newbies getting everything running.

Thanks a lot!

**Comment by Keraito** [comment]
Hey @ca057, awesome to hear that you're interested in helping out 😊 

Take a look at the `CONTRIBUTING.MD` file, it should be a great starting point for getting to work with the mono repo and kitchen sinks. Especially https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md#initial-setup this part (Initial Setup) together with (Working with the kitchen sink apps) should answer most of your questions! This will make the kitchen sink examples use your local code, instead of the installed modules when you have the dev server up. 

Hope that helps, feel free to contact me/us either here or on Slack!
