### ISSUE TITLE
"Toggle stories panel" won't re-show panel

### ISSUE THREAD

**Issue by matchu** [storybooks/storybook#4254]
### Bug or support request summary

When I use the "Toggle stories panel" keyboard shortcut to hide the stories panel, I can't re-show it again. The panel successfully hides, but issuing the same keyboard shortcut again seemingly has no effect on the panel.

### Steps to reproduce

1. Launch Storybook.
2. Use "Cmd+Shift+X" to hide the stories panel.
3. Observe that the stories panel is successfully hidden.
4. Use "Cmd+Shift+X" to show the stories panel.
5. Observe that the stories panel remains hidden, whereas I expected it to reappear.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.23
- @storybook/addon-actions 3.4.11

### Affected platforms 

- Browser: Firefox Developer Edition 63.0b8 (64-bit).
- OS: macOS Sierra 10.12.6.
```

**Comment by techieshark** [comment]
@matchu I'm curious if you still see this. I ran into the same issue - not being able to open the stories panel after having closed it, on Firefox 64bit / OS X.

I access Storybook over HTTP, but also have an HTTPS proxy to the same instance, and when accessed over HTTPS it worked.

**Comment by shilman** [comment]
@matchu @techieshark Also curious if this is happening in `^4.0.0` or `4.1.0-alpha.*`, since we've made a lot of changes since `alpha.23`.

Also, this probably unrelated but you should probably upgrade `@storybook/addon-actions` to track the same version as `@storybook/react`. We try to keep everything working together, but we don't make any special effort to make the packages work across versions, especially major version jumps like 3.x => 4.x: 
```
@storybook/react 4.0.0-alpha.23
@storybook/addon-actions 3.4.11
```

**Comment by techieshark** [comment]
@shilman Just now I happened upon the fact that the sidebar can be dragged open or closed with the mouse. I think what may have happened was somehow it became closed (possibly through my own dragging with the mouse). Then when I was trying to pop it open through the key shortcut, it was toggling between a non-existent sidebar, and a sidebar of zero width, and I just wasn't noticing the little handle appearing (it's subtle and if you weren't knowing to look for it you can miss it):

![image](https://user-images.githubusercontent.com/1072292/49782388-fcd1c780-fcca-11e8-9a36-b406c7bd3ee8.png)

![image](https://user-images.githubusercontent.com/1072292/49782402-0bb87a00-fccb-11e8-950f-cef46a3f982e.png)

So perhaps in my case this was simply 'user error'. I can't speak for @matchu though.

**Comment by deepakkadarivel** [comment]
You can use one of these 2 approaches to toggle storybook left panel:
1. Click anywhere on the canvas and press `a` -> to hide left panel and press `s` to show left panel.
2. Go to application settings in your browser and clear local storage and index db for your storybook host.

**Comment by Muneem** [comment]
It's kind of weird behaviour. There should be menu icon through which we can show or hide sidebar

**Comment by bluebrown** [comment]
WTF how is a library for building proper components showing the worst practices known to mankind? The idea of the project is good but the execution is poor. Using it since 30 minutes and I'm already annoyed.

Serious, adding a button to hide an element and removing the button together with the element... this person should be fired. Only way to get it back is a shortcut. Its killing me.

**Comment by tvvignesh** [comment]
I didn't know about this initially, so I went to localstorage and cleared everything to get the sidebar back 😅 An icon would have been great.

**Comment by hubgit** [comment]
> Click anywhere on the canvas and press `a` -> to hide left panel and press `s` to show left panel.

These days it seems that `s` is used for both hiding and showing the sidebar; `a` is used for toggling the addons.
