### ISSUE TITLE
Addon-options: What is the recommended way of setting options dynamically in v4?

### ISSUE THREAD

**Issue by binomialstew** [storybooks/storybook#4470]
I see that `@storybook/addon-options setOptions()` is now deprecated. I don't think there is a suitable replacement for the use case of changing options dynamically (not per component but as a global change).

I need to set some options in response to a button click in a decorator I have applied to my story. For example, if I want to toggle the addon panel visibility when a button is clicked. I previously had used `setOptions()` from within the decorator.

As an alternative, I found that I can use the `channel.emit()` with the  `APPLY_SHORTCUT` with `{ event: 'ADDON_PANEL' }`. The challenge is that I need to know what the state of the option so I can indicate the button style based on its state. I can track my own state in my decorator component, but this isn't reliable because other things can change the options, like the keyboard shortcut.

If there is no supported way to set options dynamically, is there a good way to get the current state of the options from within a decorator? Or is there a better solution entirely that I am missing? I went through the storybook libraries and found that the `currentOptions` state is available to the preview components through the `routes` `layout`, but I was unable to find a way to access or pass this data into my decorator.

- @storybook/addon-options: 4.0.0-alpha.24
- @storybook/core: 4.0.0-alpha.24
- @storybook/react: 4.0.0-alpha.24

- [ ] Provide alternative to deprecated setOptions?

**Comment by igor-dv** [comment]
you should use `addDecorator(withOptions(/**/));`

https://github.com/storybooks/storybook/tree/master/addons/options

**Comment by binomialstew** [comment]
@igor-dv, I'm familiar with `withOptions` and using it to set my options on initialization, but I don't understand how this can be used to set options dynamically. Your example shows `withOptions` being applied as a decorator, which will happen once when storybook is initialized.

**Comment by igor-dv** [comment]
🤔 Maybe @tmeasday can elaborate

**Comment by tmeasday** [comment]
@binomialstew -- I hadn't realised that people might have this use case. I wonder why you want to implement it via an addon rather than an addon (and have it live in the addons panel?)

@igor-dv -- interesting idea.

I'm thinking we should probably get some religion about this; as in figure out a way that all addons should
a) allow people to set parameters imperatively
b) read the current parameters

Here are my thoughts:

For a) - how to set parameters imperatively:

1.  I think in theory @igor-dv's idea should work, although it is a bit awkward to have to call `forceRerender()`. I think if we want people to call `addParameters` ad-hoc/imperatively, we should probably make it implicitly `forceRerender()`.

 If I understand @binomialstew's use case, his code snippet would be more like:

```js
.addDecorator((story, context) => {
  return (
    <div>
      <Button onClick={() => { addParameters(...) }}>...</Button>
      {story()}
    </div>
  )
});
```

 - Another option would be to add `.addParameters` (or `.changeParameters`) to the `context`. Although maybe this would have slightly different semantics -- this should probably change the parameters just for as long as the current story is on-screen.

For b) - how to read the current set of parameters:

You *could* look at `context.parameters.options` above, but that would not include

1. Options set via `setOptions()` (<- this is deprecated, though). 

Maybe we should make this call global `addParameters()` instead.

2. Options set via `addDecorator(withOptions(topLevelOptions))` (globally or per-chapter). 

This makes me wonder whether we should update the internal `makeDecorator` so that `withOptions(X)` ends up calling `addParameters(X)`.

If we do the above two things we can know for sure that parameters *always* is up to date, and users/other addon authors can examine things like `parameters.options` to know exactly what's happening (on that subject it should probably set the defaults via an implicit `addParameters` too). 

This seems like a good pattern to have in place.

**Comment by igor-dv** [comment]
I like the Idea of adding this to context. IFAIK @ndelangen has similar thoughts on changing knobs API.

**Comment by abbottdev** [comment]
Also, not sure if this is relevant but OOB if I'm using TypeScript - the Typings currently on definitely typed don't expose the `addParameters` method.

**Comment by ndelangen** [comment]
@igor-dv @kroeder were interested/working on bringing back the type definitions into the monorepo. That would solve that issue @abbottdev 

Would you possibly be able to help?

**Comment by igor-dv** [comment]
Let's continue typings discussion in #3206 =)

**Comment by abbottdev** [comment]
@igor-dv  @ndelangen  That would definitely solve the issue - I have no preference if it's definitely typed or bundled in 👍
