### ISSUE TITLE
Storybook does not respect cacheDirectory for cache location

### ISSUE THREAD

**Issue by pkuczynski** [storybooks/storybook#4665]
**Describe the bug**
Storybook creates `.cache` folder in the root of my project despite my webpack config specifies a different location for `cacheDirectory`

**To Reproduce**
1. Run storybook

**Expected behavior**
Cache folder is created in the location specified by `cacheDirectory`

**Code snippets**

Webpack config:

```
...
  module: {
    rules: [
      {
        test: /\.js?$/u,
        exclude: /node_modules/u,
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: path.join(process.cwd(), 'build/cache/babel')
          }
        }
      }
    ]
  }
...
```

**System:**
 - OS: macOS
 - Device: N/A
 - Browser: N/A
 - Framework: react
 - Version: 4.0.0

**Comment by shilman** [comment]
AFAIK this `.cache` directory is a place to store files related to a version check added in v4, and is not related to webpack.

**Comment by igor-dv** [comment]
Probably we can provide an `env` variable for this. 🤔

**Comment by pkuczynski** [comment]
How about adding this to config.js?

**Comment by igor-dv** [comment]
config.js is loaded to client, and cache dir should be provided to babel 🤷‍♂️ But it will be possible with #4169

**Comment by shilman** [comment]
@igor-dv this is not related to babel -- see my comment above. this is about version checks

**Comment by rhys-vdw** [comment]
> can you explain why you want to put this directory in a different location?

For me I don't want to add a new line to .gitignore for every module that needs a cache folder. So if there's an easy way to define this globally, or in config, I'd prefer to supply a path that is already ignored.

**Comment by rachel-md** [comment]
I have Babel caching enabled but rely on the default path of `node_modules/.cache/babel-loader`. I noticed there's also a cache file for Storybook in `node_modules/.cache/react-storybook`. Why is an additional cache folder needed at the root level? Could the two folders be combined? I too prefer to have my all my cache folders in the same location which is why `node_modules` works perfect for me.

**Comment by rhys-vdw** [comment]
Yeah, `node_modules/.cache` seems standard and is conveniently beneath the deps folder which is already ignored.

**Comment by pkuczynski** [comment]
Thanks @alex-fournier !

**Comment by shilman** [comment]
This just went out in https://github.com/storybooks/storybook/releases/tag/v4.0.9

Great work @alex-fournier!

**Comment by kubijo** [comment]
> [babel/babel#5198 (comment)](https://github.com/babel/babel/issues/5198#issuecomment-277603878)
> 
> https://babeljs.io/docs/en/babel-register#babel_cache_path=
> 
> It would be good if sb supports customizing the cache path

As a follow-up to this, I am unifying the cache directory path for our tools and storybook is the last hard-headed one that seemingly cannot be persuaded to use it (as seen in [`resolve-path-in-sb-cache.ts#L6`](https://github.com/storybookjs/storybook/blob/acbd01566c3ec19c9164e57bba3cc823cd4e4260/code/lib/core-common/src/utils/resolve-path-in-sb-cache.ts#L6))

Could you please consider introducing some solution for this to be configurable?
You are seemingly using [`find-cache-dir`](https://github.com/sindresorhus/find-cache-dir) for some cache path, but in the linked location, which results in `node_modules/.cache/storybook/{dev-server,public}` being created in my workspace root (I use Yarn's PNP mechanism, so otherwise I do not have `node_modules` at all)…
