### ISSUE TITLE
Storybook 4 color knob Not Rendering Properly

### ISSUE THREAD

**Issue by vincelawdev** [storybooks/storybook#4694]
**Describe the bug**
The colour picker of the color knob is not rendering properly. I cannot see the full colour picker to select the colour I want.

**To Reproduce**
1. Add import { withKnobs, color } from '@storybook/addon-knobs';
2. Add color={color('Colour', '#9B9B9B', 'colour')} to a component story.

**Expected behavior**
The colour picker should not be partially hidden. It should be displayed completely.

**Screenshots**
![colour-picker](https://user-images.githubusercontent.com/1631850/47892937-7d243200-deae-11e8-929f-0a091a04cf83.jpg)

**System:**
 - OS: Windows 10
 - Browser: Chrome
 - Framework: React
 - Version: 4.0.2

**Comment by a-trost** [comment]
This seems to be due to overflow hidden on the div that contains the entire knobs panel. Unchecked it displays, and it only happens at the bottom of a list of knobs. 
![image](https://user-images.githubusercontent.com/19617280/48661729-b7600880-ea44-11e8-9383-ff608109c1bc.png) This is with "Overflow:hidden" removed from that container div.

**Comment by igor-dv** [comment]
@maacky, It's still an issue
