### ISSUE TITLE
Make tracking opt-in

### ISSUE THREAD

**Issue by kentcdodds** [storybooks/storybook#474]
Would you consider making tracking opt-in? I realize that this will significantly reduce the amount of data you'll get, but I feel pretty uncomfortable with any software that sends data to a third party by default. And I'm sure I'm not alone. Feels pretty shady honestly.

I would say you could make a prompt in `getstorybook` that asks: "Are you ok helping us understand how you use react-storybook by sending us anonymous usage data?" It can even default to "Yes".

In any case, I would definitely prefer a flag that is `--track` if I _want_ to send the data, rather than have to add a flag `--dont-track` to opt-out.

**Comment by arunoda** [comment]
I got your concern. 
The thing we started this because, we need a metric of usage where we can rely and it'll help us a lot to see the actual usage of storybook. (We can't rely on NPM's install count)

Basically, we don't send any other information other than the package version installed on your app. (We even don't use even that yet)
[See.](https://github.com/kadirahq/react-storybook/blob/master/src/server/track_usage.js)

This is not like anonymous data sending or even Google Analytics. 

I get it the whole idea of your comment. 
If we don't have the usage stats, It's like we are building something in the dark.

---

Anyway, I'll think about a way satisfy both our needs.

**Comment by kentcdodds** [comment]
> It's like we are building something in the dark.

Thus is the same case for all open source software. Even React struggles with this.

**Comment by mnmtanish** [comment]
@arunoda will it help if we're more transparent about the data we collect? Make collected data itself open perhaps?

**Comment by arunoda** [comment]
@mnmtanish That's pretty great.
Shall we host that Storybook @madushan1000 built, so data is in the public :)

**Comment by mnmtanish** [comment]
It'll be awesome if we can do that :D
Better make the data set public as well

**Comment by arunoda** [comment]
Can we do that in BigQuery.

**Comment by mnmtanish** [comment]
Yeah

**Comment by arunoda** [comment]
Okay. Then it's pretty cool.
Let's do this.

**Comment by madushan1000** [comment]
Hi, This is the Google bigquery dataset for our tracking data. Anyone can access and query it(under their own expense) if they are logged into google. 
https://bigquery.cloud.google.com/dataset/kadira-storybooks:storybook_ping_data

**Comment by arunoda** [comment]
Here's the summary of all the data we collect.
See: https://stats.getstorybook.io

**Comment by kevinSuttle** [comment]
As a privacy advocate, I almost always opt-_in_ when given the opportunity. 

See Homebrew's experience with this. Being upfront is the best approach, IMO.
https://news.ycombinator.com/item?id=11566720

**Comment by ndelangen** [comment]
Tracking has been completely removed.
