### ISSUE TITLE
v4 no longer shows correct component in Story source

### ISSUE THREAD

**Issue by alisonjoseph** [storybooks/storybook#4759]
Our users rely on storybook to know how to use our components. They use the "show info" to see the component name annd prop types table. Since upgradinng to v4 we are gettinng questions about what componennt to use since it is no lonnger visible. Is this by design or a bug? and is there any way to fix. Thank you! 🙌 

This is what we get w/ v3

<img width="584" alt="screen shot 2018-11-09 at 8 09 11 am" src="https://user-images.githubusercontent.com/2753488/48267111-0f6c8e80-e3f7-11e8-8310-50bc89d4edad.png">

vs after upgrading to v4. 
<img width="669" alt="screen shot 2018-11-09 at 8 09 24 am" src="https://user-images.githubusercontent.com/2753488/48267106-0bd90780-e3f7-11e8-9f62-23b74f71c1e6.png">

**Comment by MorganLester** [comment]
Looks like you need to add displayName and that resolves it.

**Comment by vpicone** [comment]
@MorganLester The weird thing is that requirement isn't new but it worked fine before (presumably through @babel/preset-react's "@babel/plugin-transform-react-display-name"). Wondering why that preset might not work as expected when running build-storybook in v4.

**Comment by igor-dv** [comment]
I can assume there is something to do with babel minification configuration

**Comment by vpicone** [comment]
@igor-dv The minification configuration of storybook itself? This is the .storybook/.babelrc for the project. It's only an issue comes from the statically built storybook:
`
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": ["last 1 versions", "Firefox ESR"]
        }
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    "dev-expression",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-json-strings",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    "@babel/plugin-proposal-optional-chaining",
    [
      "@babel/plugin-proposal-pipeline-operator",
      {
        "proposal": "minimal"
      }
    ],
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-do-expressions"
  ]
}
`

**Comment by vpicone** [comment]
I wanted to share my findings from researching this. It seems the problem is that Storybook's webpack config uses the UglifyJSPlugin to mangle function names during `build-storybook`. As a result, the React component names get minified before being set (by @babel/react) as the displayName. The new minification was likely due to storybook's webpack 4 upgrade. 

The three potential solutions I found are:

1. Define display name on every component
2. Override the minification plugin and settings of the storybook configuration.
3. Use a babel plugin, [like this one](https://github.com/opbeat/babel-plugin-add-react-displayname), to 'magically' add the displayNames before minification

I think option 1 is the least brittle as it doesn't require an additional dependency and doesn’t rely on a 1:1 mapping of function/class name with intended displayName. This method also prevents things like forwardRef resulting in components labeled `<ForwardRef>`.

**Comment by gregoralbrecht** [comment]
I came here because I had the same issue and upgrading to `v4.1.0-alpha.12` **_kind of_** fixed it for me. The component names are no longer minified but they include their name twice (or both names for renamed components)

## With `start-storybook`
<img width="741" alt="bildschirmfoto 2018-12-12 um 10 57 22" src="https://user-images.githubusercontent.com/6179211/49861889-386cae80-fdfd-11e8-8a29-d32585f08df9.png">

## After running `build-storybook`
<img width="741" alt="bildschirmfoto 2018-12-12 um 10 57 55" src="https://user-images.githubusercontent.com/6179211/49861939-53d7b980-fdfd-11e8-8f6b-c4c3bdbc813d.png">

**Comment by nataliepan** [comment]
Im also getting the same issue with the name appearing twice

**Comment by nataliepan** [comment]
I was able to resolve this by creating .storybook/webpack.config.js that just copies the default
My components still need displayName else the double name will happen
```
const path = require("path");

module.exports = (baseConfig, env, defaultConfig) => {
  // Extend defaultConfig as you need.
  return defaultConfig;
};
```
