### ISSUE TITLE
Apply sideEffect true to default CSS rule 

### ISSUE THREAD

**Issue by ronanmulvaney** [storybooks/storybook#4918]
As per #4690 sideEffects true is needed to load SCSS but it is also needed to load CSS as per the linked https://github.com/webpack-contrib/style-loader/issues/312#issuecomment-406444631

Could this be applied to the provided CSS rule in the default WebPack config.

**Comment by igor-dv** [comment]
I think it could. Do you want to PR?

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.35 containing PR #6650 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
