### ISSUE TITLE
Ember: Uncaught TypeError: _global.window.require is not a function

### ISSUE THREAD

**Issue by musaffa** [storybooks/storybook#4957]
After running the storybook server, the following error pops up in the browser console:
```sh
Uncaught TypeError: _global.window.require is not a function
```
Originates from [this line](https://github.com/storybooks/storybook/blob/4c757d05f162925217751bb5d61518c108d0935b/app/ember/src/client/preview/render.js#L7).

**To Reproduce**
1. ember new storybook-test --yarn
2. cd storybook-test
3. npx -p @storybook/cli sb init
4. yarn build && yarn storybook

**System:**
 - OS: Ubuntu 16.04 LTS
 - Browser: Chrome, Firefox
 - Framework: Ember (3.5)
 - Version: 4.0.12
 - Node: 10.14.1
 - Yarn: 1.12.3

**Comment by igor-dv** [comment]
@gabrielcsapo, wasn't `sb cli` supposed to install `sb-ember-adapter`?

**Comment by igor-dv** [comment]
@musaffa, try to use `ember-cli-storybook` until we have a better solution.

**Comment by gabrielcsapo** [comment]
@musaffa have you tried using the quick-start guide https://storybook.js.org/basics/guide-ember/?

@igor-dv will investigate and make sure it gets added as a part of the bootstrapping process

**Comment by killabeat** [comment]
here is clean repository with this issue https://github.com/killabeat/storybook-issue-4957

**Comment by gabrielcsapo** [comment]
@musaffa what was the version of storybook you were installing?

@killabeat would you be able to go through the bootstrapping process and show where it fails? There is no stories in the specified link.

**Comment by musaffa** [comment]
Storybook version: 4.0.12

**Comment by killabeat** [comment]
@gabrielcsapo
sorry i hurried) added strories to https://github.com/killabeat/storybook-issue-4957

**Comment by barryofguilder** [comment]
I went through the steps on the Ember guide an ran into issue #4672. I solved it by running `npm i --save-dev babel-loader`. After that, I hit this issue ☹️. Anybody solve it yet?

**Comment by barryofguilder** [comment]
@killabeat the `package.json` file seems to have a lot more stuff than what you get by following the instructions in the guide.

I have followed the [Ember specific guide](https://storybook.js.org/basics/guide-ember/) which just says you have to run `npm i --save-dev @storybook/ember` and then it walks you through adding the config file, stories, etc. That will give you the error that says "Cannot find module 'babel-loader/package.json'" when you run `npm run storybook` and it tries to pull stuff from the Ember build. After manually running `npm i --save-dev babel-loader`, I get the error that says "Uncaught TypeError: _global.window.require is not a function" after storybook is launched in my browser.

I have followed the instructions from the generic [Quick Start guide](https://storybook.js.org/basics/quick-start-guide/) that says to run `npx -p @storybook/cli sb init`. This actually gets you a little further because it detects I am using Ember, so it installs storybook for Ember. It also installs `babel-loader`. But I still get an error that says "Uncaught TypeError: _global.window.require is not a function" after storybook is launched.

I'm not sure if there are some dependencies that are not added when installing storybook (using either method), or if there are some additional dependencies needed for storybook that I should just know I have to install.

**Comment by barryofguilder** [comment]
@killabeat And yes, if I clone the storybook repo and run the `ember-cli` example, it works. I'm trying to figure out what's missing between mine and that.

**Comment by barryofguilder** [comment]
I think I know what the problem is. The `.storybook/preview-head.html` file is not being generated for me. I manually created that file and used the contents from the `ember-cli` example, and it now works.

**Comment by barryofguilder** [comment]
It seems that the step missing from the guide is to manually install `ember-cli-storybook`. The guides say

> Your environment will be preconfigured using ember-cli-storybook.

But I don't think there's anything that's actually installing that addon when running `npm i --save-dev @storybook/ember`. This addon is what's responsible for creating the `.storybook/preview-head.html` file which is crucial to running Stoybook.

**Comment by barryofguilder** [comment]
@gabrielcsapo It's strange though, when running storybook the very _first_ time, `ember serve` does not create the `preview-head.html` file. I noticed that I had to run `ember build` the first time, then once the `preview-head.html` file exists, running `ember serve` before storybook will update the file accordingly.

**Comment by gabrielcsapo** [comment]
Right, `ember serve` will enable live reload, `ember build` does not enable live reload.

**Comment by barryofguilder** [comment]
@gabrielcsapo Sorry, I don't think I'm explaining it well enough.

If I follow the steps on the [Storybook for Ember](https://storybook.js.org/basics/guide-ember/) page, I get an error due to the `preview-head.html` file not being there. I have my npm scripts setup just like it says:

```
{
  "scripts": {
    "build-storybook": "ember build && build-storybook -p 9001 -s dist",
    "storybook": "ember serve & start-storybook -p 9001 -s dist"
  }
}
```

What I'm saying is, after installing Storybook and going through the guide, at the end it says:

> Now everything is ready. Simply run your storybook with: `npm run storybook`

Doing that gives me the error that this issue is talking about. It seems that running `ember serve` does **not** create the `preview-head.html` file. Running `ember build` **does** create the `preview-head.html` file. Once the file exists, running `ember serve` will **update** the file with additional stuff, but it does not create it.

That leads me to believe one of two things:

1. The `ember-cli-storybook` addon needs to be updated to **create** the `preview-head.html` file when running `ember serve`.
2. The Ember guide for Storybook needs to be updated to say that if the `preview-head.html` file doesn't exist, you must first run `ember build` (not `ember serve`) to create it.

I'm not familiar enough with Storybook yet to know which option is correct.

**Comment by joefraley** [comment]
@killabeat i tried running the integration test project https://github.com/storybooks/storybook/tree/next/examples/ember-cli and just saw errors:

```
yarn install
yarn storybook
Error: Cannot find module '../dist/server'
```

**Comment by robertsteilberg** [comment]
Still having this issue. Anyone find a resolution?

**Comment by ddoria921** [comment]
I ran into this same issue. I ran the exact steps listed in the original issue. 

I resolved it by doing the following:

1. `ember install @storybook/ember-cli-storybook`
2. Replacing the generated scripts in package.json with 
```
"build-storybook": "ember build && build-storybook -s dist",
 "storybook": "ember serve & start-storybook -p 9001 -s dist"
```
3. Run `npm run build-storybook && npm run storybook`

**Comment by gvocale** [comment]
I keep running into this issues.

I have tried to do the following in succession:
1. `ember install @storybook/ember-cli-storybook`
2. `ember build && build-storybook -p 9001 -s dist`
3. `ember serve` in one terminal
4. `start-storybook -p 9003 -s dist` in another

But I keep running into:
`_global.window.require is not a function`

The file `.storybook/preview-head.html` is there.

**Comment by TheLooseCannon** [comment]
> I keep running into this issues.
> 
> I have tried to do the following in succession:
> 
> 1. `ember install @storybook/ember-cli-storybook`
> 2. `ember build`
> 3. `build-storybook -s dist`
> 4. `ember serve` in one terminal
> 5. `start-storybook -p 9003 -s dist` in another
> 
> But I keep running into:
> `_global.window.require is not a function`
> 
> The file `.storybook/preview-head.html` is there.

I started by completing this [doc](https://storybook.js.org/docs/ember/get-started/install)

and faced the same issue

and followed this comment and had my issue fixed by following the steps in this [comment](https://storybook.js.org/docs/ember/get-started/install)

**Comment by shilman** [comment]
@gossi is there a problem in the ember docs?

**Comment by gossi** [comment]
Possibly, or in the auto-generated `scripts`. The most possible cause for this problem is, when storybook is started before ember is started. That said, there are other reasons this error is showing up, such as wrong wiring of dist files that sb is _not_ picking up.

I think, there are two use-cases:

1. Consume storybook: run one command to spin up storybook; both (ember and sb) processes run in the same terminal
2. Develop with storybook: Run the two commands separately, you can later decide which one you possibly want to restart, without affecting the other - so far this has become working well for me, dunno about others.

If this is the decision, we can drive this forward.

**Comment by gabrielcsapo** [comment]
I think option 1 would be great. We can follow what ember-cli-typescript does with TSC. We can make it so that it just works instead of having to run multiple commands for development. 

I think it is still useful to have a separate build-storybook command since that produces artifacts.
