### ISSUE TITLE
4.1 doesn't work in IE 11

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#5080]
https://storybooks-official.netlify.com shows a blank page in IE 11, without console error:

```
Expected ')'
```

And https://storybooks-official.netlify.com/iframe.html shows red box with the following error:

>Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybooks/storybook/releases/tag/v4.2.0-alpha.7 containing PR #5082 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybooks/storybook/releases/tag/v4.1.4 containing PR #5082 that references this issue. Upgrade today to try it out!

**Comment by igor-dv** [comment]
Related to this - #4099, right ?

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v4.2.0-alpha.9 containing PR #5081 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybooks/storybook/releases/tag/v4.1.6 containing PR #5081 that references this issue. Upgrade today to try it out!
