### ISSUE TITLE
Ember Error: Assertion Failed: You cannot make a new Ember.Application using a root element that is an ancestor of an existing Ember.Applicatiom

### ISSUE THREAD

**Issue by transitorytammy** [storybooks/storybook#5134]
**Describe the bug**
I am building an ember-addon and am getting this error when installing storybook in the console.

`Assertion Failed: You cannot make a new Ember.Application using a root element that is an ancestor of an existing Ember.Application`

<img width="1152" alt="screen shot 2019-01-02 at 12 08 10 pm" src="https://user-images.githubusercontent.com/1967604/50610267-34293380-0e87-11e9-8522-66f94c39c325.png">

**To Reproduce**
1. add storybook to ember-addon repository
2. open console and see above error

**Expected behavior**
No error.

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2018]
 - Browser: [chrome]
 - Framework: [ember]
 - Addons: [@storybook/addon-a11y]
 - Version: [e.g. 4.0.0]

**Comment by gabrielcsapo** [comment]
This is an error we are trying to work on to resolve with the ember-core team. It is dealing with loading the application twice, the fix is to use the add-on and make sure that the EMBER_ENVIRONMENT is set to testing and it is ensuring that fast boot is turned off.

**Comment by transitorytammy** [comment]
@gabrielcsapo you mentioned the fix to this is using the add-on.  do you mean https://github.com/storybooks/ember-cli-storybook ?  Does that mean I would remove all the npm packages I have already added given I used this set of instructions for setting up?  https://storybook.js.org/basics/guide-ember/

**Comment by gabrielcsapo** [comment]
@transitorytammy I have an RB open to update the docs to reflect the ability to use the blueprints ember-cli-storybook would you see if that helps https://github.com/storybooks/storybook/pull/5489?

**Comment by Amerr** [comment]
I did run `ember b --environment=test`
and then ran storybook script. it worked

**Comment by trotzig** [comment]
For anyone coming here with the same symptoms, I thought I'd share something that worked for us. It seems the storybook integration for ember is depending on [`ENV.APP.autoboot` to be false](https://github.com/storybookjs/storybook/blob/f2118692c7a18ea8c3676446702011d5eab941a5/app/ember/src/client/preview/render.js#L9). When storybook was running, this setting was correctly set to false. But in the build phase, it wasn't. We had to make sure to run `ember build` in an environment that set `ENV.APP.autoboot = false`. In our case, that meant:

```bash
ember build --environment test
```
If this doesn't work for you, check `config/environment.js` to make sure `autoboot` is set correctly. 

The symptoms we had except for the same `You cannot make a new Ember.Application` error being logged in the javascript console was that our login screen showed up instead of the stories. This only happened on initial load however, if you refreshed the storybook page the issue went away.
