### ISSUE TITLE
Viewport Addon: Custom viewport does not respect type

### ISSUE THREAD

**Issue by nidkil** [storybooks/storybook#5303]
**Describe the bug**

When specifying type `desktop` for a custom viewport the `Rotate` option is visible in the Viewport panel. It is not visible when you select the standard `responsive` viewport, which also has the type `desktop`.

**To Reproduce**

Add the following custom viewports:

```
import { configureViewport, INITIAL_VIEWPORTS } from '@storybook/addon-viewport'

const vuetifyViewports = {
  VuetifyLg: {
    name: 'Vuetify LG',
    styles: {
      width: '1904px'
    },
    type: 'desktop'
  },
  VuetifyXs: {
    name: 'Vuetify XS',
    styles: {
      width: '600px'
    },
    type: 'mobile'
  },
  VuetifySm: {
    name: 'Vuetify SM',
    styles: {
      width: '960px'
    },
    type: 'mobile'
  },
  VuetifyMd: {
    name: 'Vuetify MD',
    styles: {
      width: '1264px'
    },
    type: 'tablet'
  },
  VuetifyXl: {
    name: 'Vuetify XL',
    styles: {
      width: '4096px'
    },
    type: 'desktop'
  }
}

configureViewport({
  viewports: {
    ...vuetifyViewports,
    ...INITIAL_VIEWPORTS
  }
})
```

**Expected behavior**

When specifying type `desktop` for a custom viewport I expect that the `Rotate` option is not visible in the Viewport panel, just like with the standard `responsive` viewport.

**Comment by mrmckeb** [comment]
Hi @nidkil, this is because the rotate button is only hidden for that specific viewport. You can see the code here:
https://github.com/storybooks/storybook/blob/v4.1.7/addons/viewport/src/manager/components/Panel.js#L201

I understand the confusion, and it could be an idea for us to add the ability to disable the rotate button in future, but for this is expected behaviour.

Please let me know if you have any other questions.

**Comment by nidkil** [comment]
HI @mrmckeb, Thx for the quick response. Looking at the code it seems like a very minor change. Would you accept a pull request?
