### ISSUE TITLE
Failed to setup on a react native project

### ISSUE THREAD

**Issue by Chakroun-Anas** [storybooks/storybook#5309]
**Describe the bug**

Following the instructions ( https://github.com/storybooks/storybook/tree/next/app/react-native ) i could not setup storybook on a react native project.

**To Reproduce**

1. Create a new react native project
2. cd to the project
3. run npx -p @storybook/cli sb init
4. Replace the content of App.js with  export default from './storybook';
5. Execute npm run storybook ( i could not pass this step without installing core-js ).
6. Run the application on an android device: Execute react-native run-android

**Expected behavior**

The application should run without problems.

**Screenshots**

![storybook-react-native](https://user-images.githubusercontent.com/35881867/51449275-24349f00-1d23-11e9-83c7-36d9a97104f2.jpg)

**System:**
 - OS: macOS Mojave 10.14.2
 - Device: MacBook Pro (13-inch, 2017)
 - Framework: React Native 0.57.8

**Comment by fjtrujy** [comment]
Having exactly the same issue over here.

**Comment by gcaven** [comment]
Having the same issue on Android specifically. I followed [this guide for the on device UI](https://storybook.js.org/basics/guide-react-native/). Frustratingly, it only happens when remote JS debugging is disabled. Works fine on iOS.

macOS Mojave 10.14.2
Android Emulator running 8.1 (API 27), but this happens on real hardware too.
react-native: 0.57.8
@storybook/react-native: 4.1.7

**Comment by bhaskarmurthy** [comment]
Same issue.

**Comment by dslounge** [comment]
Here's how to solve it.
If you take a look at the output, you'll notice this error, right after the React object error

`'Unhandled promise rejection', { [TypeError: undefined is not a function (evaluating '_iterator[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')]`

![image](https://user-images.githubusercontent.com/492403/51727837-d201bf80-203b-11e9-806c-74dee86bb1bf.png)

This is happening because something inside storybook is iterating through Symbols, and the version of JSC shipping with android doesn't support it. The best thing to do is to make a polyfill file (as explained here: https://github.com/facebook/react-native/issues/15902#issuecomment-375521246)

Make yourself a `polyfill.js` file with this. corejs is already in your dependencies, but you might want to explicitly add it to your `package.json`.
```
// symbol polyfills
global.Symbol = require("core-js/es6/symbol");
require("core-js/fn/symbol/iterator");

// collection fn polyfills
require("core-js/fn/map");
require("core-js/fn/set");
require("core-js/fn/array/find");
```

Then import that in your `index.android.js` file (or whatever your entrypoint is). Here's how I did it in my app:
![image](https://user-images.githubusercontent.com/492403/51728060-bea32400-203c-11e9-9771-2b2632514980.png)

If you take a look at that thread, an alternative is to upgrade JSC on your android build. I'm currently too lazy to do that on my own project.

**Comment by shilman** [comment]
cc @Gongreg

**Comment by Gongreg** [comment]
@shilman, IIRC this is because of core-js version mismatch. React Native uses v1 while storybook expects v2. Do you have any suggestions for it?

**Comment by shilman** [comment]
Then hopefully this will be fixed by #4942 -- adding it to the list

**Comment by Chakroun-Anas** [comment]
Thank you @gcaven, the workaround is working perfectly.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.7 containing PR #4942 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
