### ISSUE TITLE
Angular & Knobs - DynamicModule has already been destroyed error appears when switching between components

### ISSUE THREAD

**Issue by CodeByAlex** [storybooks/storybook#5382]
**Describe the bug**
An error appears stating that the Dynamic module has already been destroyed. This is occurring on Version 5+ but is not occurring in Verison 4

**To Reproduce**
1. Create more than one component configuration
3. Switch between those components
4. You will then see the following errors: 
![image](https://user-images.githubusercontent.com/29763590/51810381-7589e480-2275-11e9-8dd6-3d02c1fbd009.png)
![image](https://user-images.githubusercontent.com/29763590/51810388-7f134c80-2275-11e9-91c7-42e0e0c25e81.png)

The following only shows up in the console once and may be unrelated:
![image](https://user-images.githubusercontent.com/29763590/51810396-8e929580-2275-11e9-9ee1-0fc5d30aab6e.png)

**Expected behavior**
The component should only be destroyed once which would stop this error from appearing in both the console and the action logger. 

**System:**
 - OS: MAC OS
 - Browser: Chrome, Safari, firefox...havent tried IE but I would assume it would show up there
 - Framework: Angular 6
 - Addons: 
@storybook/addon-notes
@storybook/addon-knobs
@storybook/addon-a11y
@storybook/addon-viewport -- sidenote - viewport is not showing up in the addons section but thats a separate issue
@storybook/addon-actions

 - Version: 5.0.0-alpha.9

**Comment by CodeByAlex** [comment]
@tmeasday do you have the link to the latest angular cli example? or could you point me in the right direction to find it

**Comment by tmeasday** [comment]
It's in the repo at `examples/angular-cli`, but a built version is here: https://next--storybooks-angular.netlify.com

**Comment by tmeasday** [comment]
This issue seems to be related to knobs -- is that what you're seeing @CodeByAlex?

I'm only seeing the error when browsing *away* from a story with a knobs decorator.

The error comes from this line: https://github.com/storybooks/storybook/blob/247dd6a35382f432a39166615fba4f3ba59add63/app/angular/src/client/preview/angular/helpers.ts#L74

I don't really know how knobs or angular work so I can only speculate about what's going on. @ndelangen care to point the right person at this one? (is it you?)

**Comment by CodeByAlex** [comment]
@tmeasday I just removed the knobs addon from addon.js and I'm still seeing the error appear as seen below:
![image](https://user-images.githubusercontent.com/29763590/52870316-911a3980-3115-11e9-87cb-4e7c68c47c1f.png)
![image](https://user-images.githubusercontent.com/29763590/52870349-a55e3680-3115-11e9-9c12-8074e6c58868.png)

**Comment by CodeByAlex** [comment]
I removed all addons and I still get the error in the console when switching between components so I don't believe that it has to do with knobs specifically:

![image](https://user-images.githubusercontent.com/29763590/52877428-f119db80-3127-11e9-977d-f9f623eb848e.png)

![image](https://user-images.githubusercontent.com/29763590/52877358-be6fe300-3127-11e9-9356-57a233d801bd.png)

**Comment by tmeasday** [comment]
@CodeByAlex turning off the addon on the manager side (what you've done there) isn't going to change the behaviour on the preview side (where the stories run).

To disable knobs in the preview, remove the `withKnobs` decorator. When i do that, I see some other errors, but the above error is gone and the stories change as I browse around.

**Comment by gaetanmaisse** [comment]
It looks like the bug is caused by too many calls to `render` function from `storybook/angular`. And some of this calls are due to `STORY_CHANGED` event listener set [here](https://github.com/storybooks/storybook/blob/next/addons/knobs/src/registerKnobs.js#L58) in knob addon. Each time a story changed knob send a message to force a rerendering, but SB core is already doing the same thing so we render function is called twice. 

I tried to removed this listener and I didn't find what can be broken 🤷‍♂️ , @ndelangen do you remember why do you introduce that in this commit https://github.com/storybooks/storybook/commit/bae5a23a9356d3e29458017877e2022167bffa5c ?

**Comment by ndelangen** [comment]
@gaetanmaisse looks like knobs should do that anymore, now that it's in the core!

Good catch, would you want to fix this?

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.7 containing PR #5753 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by strat0cast** [comment]
Hi - I'm running into the same console error when switching between the "Canvas" & "Docs" tab. I've narrowed it down to the **angularLegacyRendering: true** parameter setting in my .storybook/preview.js which is necessary in order to side-step [another issue with Angular v12+ event handlers not being called](https://github.com/storybookjs/storybook/issues/16916#issuecomment-988303119).

If I set **angularLegacyRendering** to **false**, I no longer get the following error:

![image](https://user-images.githubusercontent.com/107152368/172720453-459aadbe-7ef8-4777-a34f-aa1f1f0f8f21.png)

**TO REPRODUCE**

1. Provide the **angularLegacyRendering: true** parameter value within .storybook/preview.js
2. Create an Angular component story (MDX - not sure if this is relevant, but MDX is my approach)
3. Switch between the "Docs" & "Canvas" tabs for the component - you should see the error mentioned above

**ENVIRONMENT**
Angular = 12.2.16
Storybook = 6.4.22
Storybook addon-essentials = 6.4.22

Thanks in advance for any help.

**Comment by strat0cast** [comment]
I'm also seeing the following issue, on another component story within the same Storybook project as mentioned above.

![image](https://user-images.githubusercontent.com/107152368/172723838-23209df9-6413-49d9-9856-0f3619725698.png)

**TO REPRODUCE**
1. Provide the **angularLegacyRendering: true** parameter value within .storybook/preview.js
2. Create an Angular component story (MDX) that has one or more component declarations via the moduleMetaData decorator
3. Open the component story's "Docs" tab - you should see the error mentioned above within this comment
