### ISSUE TITLE
Fuzzy search UX

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5419]
**Describe the bug**
Fuzzy search needs enhancements to be on-par with SB4.0

**Enhancements**
- [x] The search filter should be fuzzy
- [ ] Fuzzy search should highlight letter matches
- [x] The nodes should expand on filter matches (similar to SB4.0) - let's do this as part of #5594 (@tmeasday) => https://github.com/storybooks/storybook/pull/5625
- [x]  Search input should have a button to clear the field 

**Bug**
- [ ] If you click anywhere in the Sidebar and press "/", you'll insert a '/' in the search box. This should not happen.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.2 containing PR #5625 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.5 containing PR #5702 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
