### ISSUE TITLE
[v5] Styling bugs

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5421]
**Describe the bug**
Styling bugs found from UI QA

- [x] CSS scrollbars should be revealed on hover not be omnipresent
- [x] Ensure toolbar horizontal scrollbars work 
- [x] Notifications appear underneath the Canvas/Addons area 
- [x] Add-on titles should have a system default focus not what is currently there now
- [x] Remove NotificationList:empty because it's unnecessary
- [x] Fix text overflow on [about screen notification]
- [x] Menu item "about your storybook" has a [strange hover state](https://www.dropbox.com/s/pwer157om8xartg/Screenshot%202019-01-30%2014.22.41.png?dl=0)
- [x] AboutScreen styling refinements
- [x] ShortcutsScreen styling refinements
- [x] Figure out why SVG icons are sometimes distorted (find a repro if possible)

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.3 containing PR #5650 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
cc @domyen Still more to do here?

**Comment by domyen** [comment]
Yea, the three styling bugs are still open. Will try to fix them today or tomorrow.

**Comment by ndelangen** [comment]
![screenshot 2019-02-20 at 16 02 21](https://user-images.githubusercontent.com/3070389/53101056-4dff0280-3529-11e9-9ebf-72230e1fbd8c.png)
![screenshot 2019-02-20 at 16 02 29](https://user-images.githubusercontent.com/3070389/53101059-4fc8c600-3529-11e9-9139-7515ace3cd35.png)

**Comment by ndelangen** [comment]
@domyen I think i got the scrollbars issue for you:
https://github.com/storybooks/storybook/pull/5689

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.7 containing PR #5716 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.0 containing PR #5714 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
