### ISSUE TITLE
Bundled Android application is not connecting to Web Socket server

### ISSUE THREAD

**Issue by abduzar** [storybooks/storybook#5435]
**Describe the bug**
The main actors are React Native android application and Storybook WebSocket server.
When the application is not containing JS bundle it successfully connects to local WebSocket server and shares stories to WebSocket server. In the case when the application is bundled with JS inside, it does not connect to the WebSocket server.

**To Reproduce**
1. Build the Storybook Android application with embedded JS.
2. Install the application on the emulator ( AVD )
3. Launch Storybook WebSocket server
4. Launch Android application
5. Open WebSocket server web page (by default localhost:7007)
6. Storybook is empty

**Expected behavior**
Storybook web page should contain all stories added to Android application.

**System:**
 - OS: MacOS Mojave 10.14.2
 - Device: Android Virtual Device ( Nexus 5 API 27 )
 - Framework: React Native
 - Version: 4.1.2

**Comment by Gongreg** [comment]
Hey, have you tried to explicitly pass host to the storybookUI?

The host order in prieview is:

const host = params.host || parse(NativeModules.SourceCode.scriptURL).hostname || 'localhost';

So maybe parse(NativeModules.SourceCode.scriptURL).hostname returns something that isn't correct.

**Comment by abduzar** [comment]
@Gongregyes, for android putting "localhost" explicitly, does not help. As a workaround I've used 10.0.2.2 which helped.

**Comment by abduzar** [comment]
Sorry accidentally closed

**Comment by fjtrujy** [comment]
Hello,
I can confirm that I'm suffering the same error.
One question @Gongreg , why are we using `parse(NativeModules.SourceCode.scriptURL).hostname` at all?

I have been investigating it, and I have found this PR https://github.com/storybooks/storybook/pull/1568/ but as we can see is not working in all the scenarios.

Maybe we should check if the bundle is or isn't inside, and then have different approaches.

Thanks

**Comment by Gongreg** [comment]
Hey @fjtrujy, the reason for that was:

Most CRNA users will tend to run on the phone, not emulator, and the phone can't reach the PC on localhost, leading to storybook not working when following the hello world tutorial (btw this "host" should rather be in hello world readme)

I guess there are other solutions for this.

**Comment by fjtrujy** [comment]
Thanks for your reply @Gongreg, but maybe I didn't explain properly.

As you know, we can execute Storybook in a Physical Device, having the bundle either in the machine or included in the APK/IPA.
I think that the previous response that you said, would work when you DON'T have the bundle inside of the APK/IPA.
 
If I'm not wrong, when you are installing in the specific device you must provide the URL for the host where you are executing the server.

So, the current approach won't work either if you want to install the Storybook in a Physical device with the JS bundle inside of the APK/IPA, and then start the server in a different machine (obviously) to change the stories. 
In order to make it work, you must specify the server URL anyway.

So, again my proposal is, that maybe we should check if the bundle is inside or outside, in order to use or not use `parse(NativeModules.SourceCode.scriptURL).hostname`

Thanks
