### ISSUE TITLE
Pre-Made Stories

### ISSUE THREAD

**Issue by Haaruun-I** [storybooks/storybook#5461]
I was just wondering if there was any library of pre-made stories.

**Comment by mrmckeb** [comment]
Hi @Haaruun-I, not that I know of - but I can help you get started if you have any questions. Personally, I love using the `knobs` addon, and would definitely recommend looking into that.

**Comment by mrmckeb** [comment]
I do the same in my projects, @Haaruun-I :) It's a great way to manage stories.

**Comment by leoyli** [comment]
@mrmckeb I'm wonder if we can have such feature out of the box.  However, I see there are many things to consider... Or maybe just simply document an example that might be helpful?!

Here is my implementation for the story loader, for example: 

```js
/**
 * a story loader function factory with the automatic story generator
 *
 * @param {Boolean} auto - should drive stories automatically
 * @param {String[]} excluded - a blacklist array contains exclusive path fragments
 * @return {Function} - a loader function
 *
 * @see https://webpack.js.org/guides/dependency-management/#require-context
 */
export const loadStories = ({ auto = true, excluded = [] }) => () => {
  const req = require.context('@src', true, /.*\/.*\/[A-Z].*(?<!\.test|\.spec).[jt]sx$/);
  const files = req.keys();
  const stories = files.filter((path) => path.includes('.stories.js'));

  // load predefined stories
  stories.forEach(req);

  // classify and drive stories automatically
  if (auto === true) {
    const existed = new Set(stories.map((path) => path.replace('.stories', '')));
    files
      .filter((path) => !existed.has(path) && !excluded.some((str) => path.includes(str)))
      .map((path) => [
        path
          .split('/')
          .splice(1, 2)
          .join(':'), // <- this matching with mine `addon-options` configs
        req(path).default,
      ])
      .forEach(([nodeName, C]) =>
        storiesOf(nodeName, module).add(C.displayName || C.name, makeStoryOf(C))
      );
  }
};
```

```js
// @config.js
configure(
  loadStories({
    auto: true,
    excluded: ['/containers', '/routing'],
  }),
  module
);
```

Note: `@src` uses the WebPack alias, and `makeStoryOf` is the implementation details on how the story being generated.

A dummy example for `makeStoryOf`:
```js
const makeStoryOf = (C) => h(C, null, null);  // h is the `createElement` API used in React or Vue
```

This way is really good when we want to quickly compose a new presentational component, since HMR will watch the folder and the loader can generate the story automatically, especially when we have `addon-smart-knobs` used together. However, I have my own version of smart knob since the one under this project is not listed as an official add-on and not worked as I wished because I write SFC with `styled-components` in React, cc to @ndelangen ).

I would be happy to submit a PR in my free time to improve the documentation 😄, but I'm not sure where to add and what is the boundary of the context... since `makeStoryOf` is pretty customized in my use case. But I do think such feature that composes stories automatically can improve the DX in general for people using Storybook and if we want to promote CDD approach.

**Comment by mrmckeb** [comment]
I think examples in documentation would be a great way to go, and perhaps a hint in the default config that points to that documentation for copy-and-paste configs?

**Comment by Haaruun-I** [comment]
@leoyli I cant find the experimental branch

**Comment by leoyli** [comment]
Not sure about @storybook/html, that experimental branch is my own repo... I'm trying to integrate storybook into our tech stack in the company... That is why I shared the above code. I believe it is fairly straightforward to understand. I will submit a PR to improve the doc too :)
