### ISSUE TITLE
Dev mode doesn't work in IE11

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#5472]
**To Reproduce**
`yarn start`, open page in IE11, you get blank page with "Invalid character" error in console.

The reason is [`safe-eval`](https://github.com/hacksparrow/safe-eval/blob/master/index.js#L7-L17) package using template literals

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-beta.4 containing PR #5498 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Hypnosphi** [comment]
It turned out that fix from #5498 doesn't work because `safe-eval` has arrow function in the injected code: https://github.com/hacksparrow/safe-eval/blob/master/index.js#L11. This is inside a string so it doesn't get transpiled by Babel. The package's docs say that it should be used only in Node. I've opened an issue for telejson https://github.com/storybooks/telejson/issues/4

**Comment by Hypnosphi** [comment]
To reproduce the issue, you need to set a theme (e.g. `setOptions({ theme: themes.dark })`), and open Accessibility addon panel in IE11

**Comment by Hypnosphi** [comment]
Not observed in 5.0
