### ISSUE TITLE
Tooltip does not disappear when clicking in the Preview iframe

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5593]
**Describe the bug**
Open tooltips do not disappear when clicking into the Preview iframe

**To Reproduce**
1. Click on the menu tooltip to open it
2. Then click on the Preview iframe
3. See error

**Expected behavior**
Tooltips should disappear when clicking into the Preview iframe

**Screenshots**
Gif: https://cl.ly/42ce365b9d66

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.8 containing PR #5807 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
