### ISSUE TITLE
Background and viewport addons should have active states in the Toolbar

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5596]
**Describe the bug**
The "IconButtons" for Background and Viewports should have active states when they are active. Maybe abstract this behavior so other addons can use it as well?

**To Reproduce**
1. Change the Background or Viewport by clicking on one of [these buttons](https://cl.ly/b2ea5fc73119)
2. See that they are not highlighted despite the user having activated them

**Expected behavior**
The Background and Viewports icons should have an active state that looks like [this](https://www.dropbox.com/s/n9p3qzwb2rlgbzn/Screenshot%202019-02-14%2019.41.48.png?dl=0) so that users can discern when they're activated.

**Comment by ndelangen** [comment]
I'm on it

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.7 containing PR #5749 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
