### ISSUE TITLE
Version check should ensure we aren't on a newer version

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#5621]
We should use semver to check the version is actually newer.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.2 containing PR #5638 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
