### ISSUE TITLE
Update Storybook options documentation in addons/options and the main docs

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5671]
**Describe the bug**
Some options are no longer supported in 5.0. What's more, the `addParameters` API from `@storybook/yourframework` obviates the need for having the addon afaict.

If the [options addon](https://github.com/storybooks/storybook/tree/next/addons/options#set-options-globally) is deprecated, let's remove it or add messaging to direct folks to the right place.

**Expected behavior**
- Options that aren't supported are removed
- SB options should be documented in the main docs not [addons/options](https://github.com/storybooks/storybook/tree/next/addons/options#set-options-globally) docs.

I believe @tmeasday worked on `addParameters`, what do you think?

Related https://github.com/storybooks/storybook/issues/5665

**Comment by tmeasday** [comment]
Yes, this is exactly right. We should keep `withOptions` (deprecated) for this major, and if there are options that are no longer supported it's a chance to warn people that they have no effect.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.7 containing PR #5758 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
