### ISSUE TITLE
Code formatting in v5 notes addon

### ISSUE THREAD

**Issue by B3zo0** [storybooks/storybook#5726]
**Describe the bug**
I've noticed that the styling of code blocks in markdown files is rendered with syntaxhighlighter.
Problem is I have some text that look like this: 
![v5-markdown-notes](https://content.screencast.com/users/Bezoo/folders/Jing/media/8742bc3e-eeab-4e74-a61f-744a982750df/2019-02-22_1627.png)

**To Reproduce**
Use a markdown note like this https://github.com/SenseNet/sn-client/blob/master/examples/sn-react-component-docs/notes/viewcontrols/BrowseView.md with notes addon

**Expected behavior**
I expect to see inline code blocks like in github.
![github markdown](https://content.screencast.com/users/Bezoo/folders/Jing/media/bf8594e1-7882-43ad-9ec9-de0b0ae11046/2019-02-22_1842.png)
Or a way to disable copyable code block.

**System:**
 - Browser: chrome
 - Addons: Notes
 - Version: 5.0.0-rc.4

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.9 containing PR #5802 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
