### ISSUE TITLE
Fix font-family syntax in Angular welcome

### ISSUE THREAD

**Issue by MattPetitt** [storybooks/storybook#5739]
There's a typo in the angular welcome page css where `fontFamily` should be `font-family`.
https://github.com/storybooks/storybook/blob/e8cdeb6371e69ad8c83c743e9e99cf7ff31951dd/app/angular/src/demo/welcome.component.ts#L42

This causes fonts in the angular welcome page to fallback to the default.

I'm happy to contribute the fix, just wanted to leave this ticket here until I got around to it.

**Comment by Armanio** [comment]
Any PR welcome!

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.11 containing PR #6193 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.4 containing PR #6193 that references this issue. Upgrade today to try it out!
