### ISSUE TITLE
getReactScriptsPath not detecting my forked react-scripts package

### ISSUE THREAD

**Issue by d3bgger** [storybooks/storybook#5801]
I'm trying to make storybook detect my forked cra package (based on cra 2.1.5) with no luck.

The following code in getReactScriptsPath() (https://github.com/storybooks/storybook/blob/be544bc22043da83300523b59c7734ba54db1eae/app/react/src/server/cra-config.js#L13) always returns the hardcoded 'react-scripts' because it always trying to find a package.json in node_modules folder (2 folders up from /.bin/react-scripts).  How is this supposed to work?

`const reactScriptsScriptPath = _fs.default.realpathSync(_path.default.join(appDirectory, '/node_modules/.bin/react-scripts'));

  reactScriptsPath = _path.default.join(reactScriptsScriptPath, '../..');

  const scriptsPkgJson = _path.default.join(reactScriptsPath, 'package.json');

  if (!_fs.default.existsSync(scriptsPkgJson)) {
    reactScriptsPath = 'react-scripts';
  }`

thanks in advance

**Comment by sergeyzwezdin** [comment]
Hello!

We are also use forked CRA with storybook.

As @d3bgger mentioned [the problem](https://github.com/storybooks/storybook/blob/next/app/react/src/server/cra-config.js#L17-L19) with `realpathSync`:
1. On Mac it works like a charm because of `node_modules/.bin/react-scripts` is a symlink. So `realpathSync` resolves the path to target package correctly.
2. On Windows though it has some problems. Since `node_modules/.bin/react-scripts` is not symlink it doesn't resolve the target path correctly. As a result, Storybook tries to find it as `node_modules/react-scripts` which is wrong (there is no `react-scripts` folder since we have our custom package name). So, Storybook displays warning that it uses default webpack config, not from CRA.

```
info => Using base config because react-scripts is not installed.
```

![image](https://user-images.githubusercontent.com/800755/54822780-81b77e80-4cc7-11e9-8266-b8a0f6d2add4.png)

So, need to fix it somehow to find a real path of react-scripts on Windows.

@shilman you've marked the issue as "feature request", but it's actually the bug.

**Comment by shilman** [comment]
@sergeyzwezdin Does it work with CRA on Windows? If not, then it's a bug. If it works with CRA and does not work with a CRA fork, then it's a feature request since we don't claim to support that use case. As for `relpathSync`, if you have any workarounds we'd be more than happy to take a PR to support this.

**Comment by d3bgger** [comment]
> @sergeyzwezdin Does it work with CRA on Windows? If not, then it's a bug. If it works with CRA and does not work with a CRA fork, then it's a feature request since we don't claim to support that use case. As for `relpathSync`, if you have any workarounds we'd be more than happy to take a PR to support this.

Isn't this the PR adding support for CRA forks? 
https://github.com/storybooks/storybook/pull/4712

**Comment by sergeyzwezdin** [comment]
> Isn't this the PR adding support for CRA forks?

Yes, but it assumes that `.bin/react-scripts` is symlink which is wrong for Windows.

I've created another PR #6235, hope you'll merge it.

**Comment by shilman** [comment]
@sergeyzwezdin Awesome, thanks so much for this! Reviewing it now 👍

**Comment by shilman** [comment]
@d3bgger @sergeyzwezdin Didn't realize that we already were trying to support this. Bug it is then 😄

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.13 containing PR #6236 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.4 containing PR #6236 that references this issue. Upgrade today to try it out!

**Comment by sergeyzwezdin** [comment]
@shilman Thank you for quick release!
