### ISSUE TITLE
SB5: Actions panel not clearing between stories

### ISSUE THREAD

**Issue by asiacomeau** [storybooks/storybook#5932]
**Describe the bug**
After upgrading to Storybook 5, the Actions panel does not clear out when I switch between stories. This happens both when omitting `clearOnStoryChange` from storybook config, and when setting it to `true`.

**To Reproduce**
1. Go to a story that dispatches actions
2. Cause the action to be dispatched (the action shows up in the actions panel)
3. Go to another story and view the action panel
4. The previous story's dispatched actions are still listed.

**Expected behavior**
The actions panel should be cleared out when I navigate to another story.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react
 - Addons: actions (also info, knobs, storyshots)
 - Version: 5.0.0

**Comment by benjamind** [comment]
This appears to be due to the options check on the actions stored in the actions panel. The default/global config is not being copied into each action, but the check is being done against the first action in the log. You can currently work around this by setting the config options on every action you log to have the `clearOnStoryChange: true` option, then the log will properly clear.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.4 containing PR #6438 that references this issue. Upgrade today to try it out!
