### ISSUE TITLE
Addon-a11y: dark theme report

### ISSUE THREAD

**Issue by Armanio** [storybooks/storybook#6025]
**Describe the bug**
Reports in dark theme has white text on white bg.

**To Reproduce**
Open cra-kitchen-sink with dark theme
Open a11y addon
Show reports

**Expected behavior**
White text on dark bg

**Screenshots**
<img width="648" alt="Снимок экрана 2019-03-11 в 23 59 18" src="https://user-images.githubusercontent.com/3195714/54157599-b3c01980-4459-11e9-8e3d-9208583c4fe9.png">

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.5 containing PR #6026 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
