### ISSUE TITLE
Svelte still not supported.

### ISSUE THREAD

**Issue by equinusocio** [storybooks/storybook#6071]
**Describe the bug**
@Hypnosphi Svelte Js still not supported through automatic init. I followed [this guide](https://storybook.js.org/docs/guides/guide-svelte/) but i get an error:

```
The provided project type was not recognized by Storybook.

The project types currently supported by Storybook are:

    - angular
    - ember
    - html
    - marko
    - meteor
    - mithril
    - polymer
    - preact
    - react
    - react_native
    - react_project
    - react_scripts
    - riot
    - sfc_vue
    - vue
    - webpack_react
```

**To Reproduce**
1. Run `npx -p @storybook/cli sb init --type svelte`

**Expected behavior**
Storybook folder is generated inside the project root

**System:**
 - Framework: Svelte 2.16.1
 - Version: @storybook/svelte 5.0.1

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.13 containing PR #6132 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
