### ISSUE TITLE
Theming: 'brandImage' doesn't account for .svg (missing base size)

### ISSUE THREAD

**Issue by BennyZ28** [storybooks/storybook#6151]
If in my theme I declare an .svg as my brand image, nothing appears:

![image](https://user-images.githubusercontent.com/9951954/54535625-d20ca480-4986-11e9-9d21-5467ac9dbe01.png)

The fix is pretty simple:

![image](https://user-images.githubusercontent.com/9951954/54535709-02544300-4987-11e9-87e4-f9e5769eafa1.png)

![image](https://user-images.githubusercontent.com/9951954/54535722-084a2400-4987-11e9-8583-cbd0575140ff.png)

**Comment by shilman** [comment]
AFAIK fixed in https://github.com/storybooks/storybook/pull/5904

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.10 containing PR #5904 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
