### ISSUE TITLE
[addon-knobs] multiple color selectors obscure selection popup

### ISSUE THREAD

**Issue by Zyzle** [storybooks/storybook#6184]
**Describe the bug**
If more than one colour selection knob is added to a story the popoup selector is obscured by the subsequent colour selector knob control

**To Reproduce**
Adding multiple colour selection knobs to a story in such a way that they appear close enough to each other in the controls tab is enough.

**Expected behavior**
Popover selection control should appear in front of subsequent controls

**Screenshots**
![Screenshot 2019-03-19 at 14 26 29](https://user-images.githubusercontent.com/3787524/54614116-c9ce6b00-4a53-11e9-807d-3bcdff3bae1f.png)

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: reproduced in chrome and safari
 - Framework: react
 - Addons: knobs
 - Version: 5.0.3

**Comment by Armanio** [comment]
Ok, no problem. 🤔

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.11 containing PR #6203 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.4 containing PR #6203 that references this issue. Upgrade today to try it out!
