### ISSUE TITLE
SB fail on browser window resize

### ISSUE THREAD

**Issue by Armanio** [storybooks/storybook#6507]
**Describe the bug**
Like in [this](https://github.com/storybooks/storybook/issues/5910) issue, but if you add jest addon you get a fatal error.

**To Reproduce**
Run cra-kitchen-sink
Resize browser window to less 600px
See error

**Expected behavior**
Mobile view

**System:**
 - OS: any
 - Device: any
 - Browser: any
 - Framework: any
 - Addons: jest
 - Version: 5+

**Additional context**

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.27 containing PR #6508 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
