### ISSUE TITLE
groupId doesnot work in `files` in @storybook/addon-knobs

### ISSUE THREAD

**Issue by JennerChen** [storybooks/storybook#6520]
**Describe the bug**
groupId doesnot work in `files` in @storybook/addon-knobs

**To Reproduce**
```
import { files } from "@storybook/addon-knobs";
const groupId = "configuration";
const logoUrl = files("logo", "*",null, groupId);
// logoUrl doesnot show in Configuration tab, see screenshot
```

**Expected behavior**
files goes to configuration groupId

**Screenshots**
![image](https://user-images.githubusercontent.com/5472912/56121806-83612300-5fa3-11e9-9650-04877b6dd55e.png)

**Additional context**
@storybook/addon-knobs v5.0.7

**Comment by JennerChen** [comment]
https://github.com/storybooks/storybook/blob/cd20c4b75d4cddc6d596e381360efe0020c4bff9/addons/knobs/src/index.js#L72-L74

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.28 containing PR #6534 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.9 containing PR #6534 that references this issue. Upgrade today to try it out!
