### ISSUE TITLE
warning about opn/open seen during yarn install

### ISSUE THREAD

**Issue by kaiyoma** [storybooks/storybook#6565]
When installing the latest version of Storybook (5.1.0-alpha.27), this warning is seen in the output of `yarn install`:

```
warning @storybook/core > opn@6.0.0: The package has been renamed to `open`
```

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.32 containing PR #6567 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
