### ISSUE TITLE
remove hard coded title for each story

### ISSUE THREAD

**Issue by bryankang** [storybooks/storybook#6590]
must've went through from the recent refactor

https://github.com/storybooks/storybook/blob/v5.1.0-alpha.33/app/react-native/src/preview/components/StoryListView/index.tsx#L151

**Comment by benoitdion** [comment]
Good catch @bryankang. Thanks for reporting!

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.34 containing PR #6599 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
