### ISSUE TITLE
[Addon-contexts] Vue integration improvement

### ISSUE THREAD

**Issue by leoyli** [storybooks/storybook#6631]
**Is your feature request related to a problem? Please describe.**
Due to how Vue define it's component, the component props in Vue is a bit different from React.  For example, `class` and `style` have its own top-level field in [the component data object](https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth). To make it more JSX-friendly, the `props` definition need a special transformation for integrating Vue. This will makes the `addon-contexts` able to inject HTML attributes like the one in React.

**Describe the solution you'd like**
Improve the framework binding, and add example for Vue-kitch-sink.

**Describe alternatives you've considered**
N/A

**Are you able to assist bring the feature to reality?**
Have been done.

**Additional context**
Merge request follows up.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.35 containing PR #6632 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
