### ISSUE TITLE
[Addon-contexts] Add Preact Support

### ISSUE THREAD

**Issue by leoyli** [storybooks/storybook#6659]
**Is your feature request related to a problem? Please describe.**
Preact is a small subset of React that aiming to be 100% compatible with React.  The API is kind of similar to React.

**Describe the solution you'd like**
Add Preact support, which should be just a no brainer.

**Describe alternatives you've considered**
N/A

**Are you able to assist bring the feature to reality?**
Done

**Additional context**
N/A

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.36 containing PR #6660 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
