### ISSUE TITLE
v5.0.11: addon-knobs with periods and square brackets in the label should properly display

### ISSUE THREAD

**Issue by ssilk** [storybooks/storybook#6694]
**Describe the bug**
When the first knob in a story has either a period or a square bracket in its label string argument, additional knobs do not display.

**To Reproduce**
To reproduce the behavior:

Create a Story using knobs, adding a period and/or square bracket(s) to the label of the first knob ->

```
import React from 'react'

import { storiesOf } from '@storybook/react'
import { text } from '@storybook/addon-knobs'

cont MyStory = () => {
  const knobOne = text('knob.One', 'Knob One')  // or use label 'knob[One]'
  const knobTwo = text('knob two', 'Knob Two')

  return (
    <p>
      {knobOne}
      {knobTwo}
    </p>
  )
}

storiesOf('Sample', module).add('My Story', MyStory)
```

**Expected behavior**
That when the story is run, both of the knobs display in the knobs panel:

- knob.One
- knob two

**Actual behavior**
Only the first knob displays in the knobs panel:

- knob.One

**System:**
 - OS: OS X 10.14
 - Device: Macbook Pro 2018
 - Browser: Chrome
 - Framework: React
 - Addons: addon-knobs
 - Version: 5.0.11

**Comment by leoyli** [comment]
duplicated #6526.

Hello, thank you for reporting this bug to us.  Since I have reported this bug in our issue tracker already, I will close this issue.  Feel free to drop your idea or even step in to see if you can find a quick fix there.  If I were remembered correctly, we will have knob totally rewritten (v2) later at some point... (cc to @ndelangen).
