### ISSUE TITLE
Support svelte v3 components

### ISSUE THREAD

**Issue by cam-stitt** [storybooks/storybook#6697]
**Is your feature request related to a problem? Please describe.**
Svelte has recently release version 3, which is a complete overhaul of the syntax and API.

**Describe the solution you'd like**
A migration to support svelte v3 and removing support for svelte v2.

**Describe alternatives you've considered**
I have not looked at having support for both v2 and v3. Considering the backward incompatible nature of svelte v3, I don't think it would be simple.

**Are you able to assist bring the feature to reality?**
yes, I can...

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.40 containing PR #6698 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
