### ISSUE TITLE
fusebox support?

### ISSUE THREAD

**Issue by ConneXNL** [storybooks/storybook#694]
Fusebox ( https://github.com/fuse-box/fuse-box ) claims to have much fast build-times than Webpack. Since React storybook allows us to work in an isolated environment and is mainly for development, it might be interesting to look into running Storybook via Fusebox and hopefully get a performance gain.

What would it take to run Storybook via Fusebox?

**Comment by alloy** [comment]
I did a naive port inside my project that does just what we need, for now. It’s very much faster than the webpack setup.

https://github.com/artsy/reaction-force/pull/17

**Comment by guycreate** [comment]
Thanks @alloy, that inspired me to add it to my [create-react-app](https://www.npmjs.com/package/fuse-box-create-react-app) fork.    Now you can do a `create-react-component mycomponent` and get a pre-configured Fuse-Box component that uses Storybook for the dev server.    Still a work in progress, but using it myself; feedback / contributions welcome.  Is indeed very much faster than webpack. 

``` bash
npm install -g fuse-box-create-react-app
create-react-component TestComponent
cd TestComponent
npm start
```
and to upload your new component on gh-pages:

```bash
npm run build
npm run deploy
```

**Comment by ndelangen** [comment]
Not something we can do on a whim, we expose an API for extending our webpack config, or over-riding it completely. So switching away from webpack would be hard.

I'm interested how this could be solved. Webpack has tremendous traction and a huge community, it's likely webpack will evolve to become faster like fusebox, like what happened with tree-shaking & roll-up.

Not closing this, because a proof of concept is very much welcome! 
If it's possible somehow to enable fusebox for projects not extending the webpack config, that would be an options. It would mean maintaining 2 build-configs in our codebase...
