### ISSUE TITLE
Auto-load addons

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#764]
We could load all addons we know `@storybook/addon-**` and the community developed ones `storybook-addon-**` by reading the `package.json`.

**Comment by tmeasday** [comment]
I think "automagic" like this hurts more than it helps. People don't really understand how it works and so when they have problems they don't have any clue how to fix them.

It doesn't seem worth it to save a one line `import '@kadira/storybook-addon-notes/register';` (etc)

**Comment by UsulPro** [comment]
In general I like the idea of lowering the barrier to entry. Take a look at [storybook-addon-material-ui](https://github.com/sm-react/storybook-addon-material-ui). It's more `Material-UI` tool then `Storybook`, and people coming from there maybe never use `Storybook` before. So making their life easier is make sense for me.

On the other hand, in addition to registering the addon, we need some templates. That's why I'd like to have some API like `$ getstorybook storybook-template-material-ui`

**Comment by ndelangen** [comment]
@UsulPro Can you make a note about templates on this issue: #1108 

@tmeasday Do you recommend we do not do this?

**Comment by tmeasday** [comment]
That is my recommendation, yes. Not so wedded to it that I would complain if we wanted to go another way, but this is based on my experience with other OSS projects.

**Comment by shilman** [comment]
Definitely with @tmeasday on this one, and for the same reasons (cough, Meteor, cough)
