### ISSUE TITLE
How to use two addons with custom add function at once

### ISSUE THREAD

**Issue by methyl** [storybooks/storybook#766]
Let's say I want to use both https://github.com/storybooks/react-storybook-addon-info and https://github.com/evgenykochetkov/react-storybook-addon-props-combinations

Is there currently any sane way to do that? Both are relying on their own `add` function, so I'm not sure how one can use both.

**Comment by UsulPro** [comment]
@methyl Thanks for your question! 

This is a great issue, which should have been raised sooner or later. Unfortunately, this is not possible at the moment. But I think we should definitely add this feature to our *roadmap*, since increasing the number of addons, it will be more and more in demand.

Looks like we can consider the following approaches for that:

- provide special method `.addCombination` to `storiesOf` 

- use metadata like in #705

any other ideas?

Not sure that all addons can be combined in this way though

**Comment by UsulPro** [comment]
@methyl  If you are looking for a personal way of using these addons together, you can do it by creating your own extension via `setAddon()` API as a workaround.

You can find an example [here](https://github.com/sm-react/storybook-chapters/blob/master/src/chapters/addon.js#L60)

If you'll need any help with that feel free to ask me)

**Comment by ndelangen** [comment]
#1209 We should find better ways, I think making custom `addWithAddon1AndAddon2AndAddon8()` is not scalable.
