### ISSUE TITLE
Add pop-out button to open preview in a new window

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#862]
<a href="https://github.com/mnmtanish"><img src="https://avatars2.githubusercontent.com/u/136691?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mnmtanish](https://github.com/mnmtanish)**
_Saturday Jul 02, 2016 at 02:24 GMT_
_Originally opened as https://github.com/storybooks/storybook-ui/issues/10_

----

It seems it can be useful in some use-cases if we can use a new window for the preview instead of an iframe:
- https://github.com/kadirahq/react-storybook/issues/292

CC: @ritz078

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Saturday Jul 02, 2016 at 02:54 GMT_

----

I think this should be a keyboard shortcut. Button would work too, if we can find a good place to put it.

**Comment by UsulPro** [comment]
I suppose we could put it into this menu #867

**Comment by ndelangen** [comment]
There's full-screen mode.
There's already a keyboard shortcut for it.

So this would add a button to switch to full-screen mode.. because actually popping the preview out seems odd, what will take it's place?

I would like a button that will open an **additional** preview. But that's an other issue #1335 

Given @UsulPro's PR is already open, and is larger in scope then this issue, I'm going to go ahead an close this.
