### ISSUE TITLE
Support Immutable.JS props / customize props serializer

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#933]
<a href="https://github.com/MrOrz"><img src="https://avatars0.githubusercontent.com/u/108608?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MrOrz](https://github.com/MrOrz)**
_Tuesday Aug 09, 2016 at 08:49 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/48_

----

Currently, when ImmutableJs instances are passed to props or set as default props, cryptic information may be shown:
![2016-08-09 12 18 41](https://cloud.githubusercontent.com/assets/108608/17509945/1deb067e-5e4f-11e6-97e2-a44432fa5926.png)

Currently I have temporarily [monkey-patched `<PropVal />`](https://github.com/MrOrz/react-storybook-addon-info/commit/c74d6d97ebb59d526b012c37089e11498b7fe6f2#diff-d54f967651cd0741dbae9b74fd8ed084) for my own use. However, I think we can do more than just supporting ImmutableJS; if we let the users to customize the props serializer, any type of custom objects can be displayed in a more informative form.

For now I am not sure how useful it would be, nor do I have any idea about how the API should look like. It would be great if we have more discussion here :)

**Comment by shilman** [comment]
<a href="https://github.com/Dharmoslap"><img src="https://avatars1.githubusercontent.com/u/3543614?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Dharmoslap](https://github.com/Dharmoslap)**
_Tuesday Feb 07, 2017 at 11:18 GMT_

----

Any progress on this one? Thanks

**Comment by MrOrz** [comment]
Sorry for not writing back for so long.

Since my [last patch](https://github.com/MrOrz/react-storybook-addon-info/commit/c74d6d97ebb59d526b012c37089e11498b7fe6f2#diff-d54f967651cd0741dbae9b74fd8ed084) storybook has changed a lot. Seems that developers can now set [options that directly goes to `<PropVal>`](https://github.com/storybooks/storybook/blob/master/addons/info/src/components/PropVal.js#L147).

How about adding an option like `customPropSerializer` that takes a callback function which:
* The function should takes `props.val` and returns a string or React element.
* When the function returns `undefined`, `<PropVal>` uses its original way to render.
* Otherwise, `<PropVal>` renders the returned result of `customPropSerializer`.

In this way, I can implement my own serializer for Immutable.js prop values, and leaves the rest of the prop value types to the original `<PropVal>` implementation.
