### ISSUE TITLE
composing webpack configs using webpack-blocks a good idea?

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#964]
I've heard good things about https://github.com/andywer/webpack-blocks.

Maybe we should try it so possibly extending storybook's webpack config can become easier?

**Comment by wardpeet** [comment]
what is wrong with a plain webpack config? relying on a third party project is not a great idea, if a new webpack version gets out you will have to wait until webpack blocks support it?

If you like I can give it a spin to upgrade to webpack 2.

**Comment by danielduan** [comment]
I think this has a valid use case, even when just dealing with our default webpack configs.

Right now, we have a set of base configs in `config/webpack.config.js` that defines the entry points and a .jsx loader. It gets imported into `config/default/webpack.js`and we throw a bunch of  loaders for files like .css, .jpeg/png, etc.

At the moment, there's no way to import the default configs except the .jpeg/png loader or override our postcss-loader config with a custom one. You either take the base config or full config since the loaders and plugins are in arrays and removing them gets a bit tricky.

**Comment by wardpeet** [comment]
it's doable with webpack-merge.

**Comment by ndelangen** [comment]
This issue is now about wether our webpack config should be configurable, because our webpack config **is extendable in a few ways already**:

- you can provide an object as a config, and we'll merge our and your config together.
- you can provide a function and we'll call it with ours. whatever you return we will pass to webpack. 
- you can provide a function and just return whatever you want and ignore our config.

See an example of using a function here:
https://github.com/storybooks/storybooks.github.io/blob/update-docs-to-3.0.0/.storybook/webpack.config.js

---

Point is, merging webpack configs together (either we do it, or you do it in a function) can be quite complex / hands-on. Maybe it's a good idea to do this via some tool like webpack-blocks.

I'm not so sure myself. I feel the same way as @wardpeet about this. I don't want to over-engineer webpack configs, when they are considered too complex already by some people I know. But give it up-votes if you want it, and we will have a look.

**Comment by wardpeet** [comment]
I like  https://github.com/storybooks/storybooks.github.io/blob/update-docs-to-3.0.0/.storybook/webpack.config.js as it's still webpack to it's core.

**Comment by danielduan** [comment]
Whatever we decide to do, we should try to give as many examples as possible in our docs. A good portion of the issues opened in the repo is webpack related questions. We shouldn't expect users to go into our code base and read the source files to figure out how to configure a loader.
